// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "../ui.h"

void ui_ScreenLoadAQI_screen_init(void)
{
    ui_ScreenLoadAQI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoadAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenLoadAQI, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenLoadAQI, lv_color_hex(0x18191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLoadAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoad = lv_obj_create(ui_ScreenLoadAQI);
    lv_obj_remove_style_all(ui_ContainerLoad);
    lv_obj_set_width(ui_ContainerLoad, 800);
    lv_obj_set_height(ui_ContainerLoad, 480);
    lv_obj_set_align(ui_ContainerLoad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLoad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerStatus = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerStatus);
    lv_obj_set_width(ui_ContainerStatus, 800);
    lv_obj_set_height(ui_ContainerStatus, 47);
    lv_obj_set_align(ui_ContainerStatus, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContaierStatusLeft = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContaierStatusLeft);
    lv_obj_set_width(ui_ContaierStatusLeft, 54);
    lv_obj_set_height(ui_ContaierStatusLeft, 21);
    lv_obj_set_x(ui_ContaierStatusLeft, 32);
    lv_obj_set_y(ui_ContaierStatusLeft, 14);
    lv_obj_clear_flag(ui_ContaierStatusLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_ContaierStatusLeft);
    lv_obj_set_width(ui_LabelTime, 54);
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "9:41");
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerStatusRight = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContainerStatusRight);
    lv_obj_set_width(ui_ContainerStatusRight, 79);
    lv_obj_set_height(ui_ContainerStatusRight, 13);
    lv_obj_set_x(ui_ContainerStatusRight, -32);
    lv_obj_set_y(ui_ContainerStatusRight, 19);
    lv_obj_set_align(ui_ContainerStatusRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ContainerStatusRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMobileSignal = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerMobileSignal);
    lv_obj_set_width(ui_ContainerMobileSignal, 18);
    lv_obj_set_height(ui_ContainerMobileSignal, 12);
    lv_obj_set_align(ui_ContainerMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerMobileSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMobileSignal = lv_img_create(ui_ContainerMobileSignal);
    lv_img_set_src(ui_ImageMobileSignal, &ui_img_images_mobilesignal_png);
    lv_obj_set_width(ui_ImageMobileSignal, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageMobileSignal, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_ImageMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifiSignal = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerWifiSignal);
    lv_obj_set_width(ui_ContainerWifiSignal, 17);
    lv_obj_set_height(ui_ContainerWifiSignal, 12);
    lv_obj_set_x(ui_ContainerWifiSignal, 26);
    lv_obj_set_y(ui_ContainerWifiSignal, 0);
    lv_obj_set_align(ui_ContainerWifiSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerWifiSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifiSignal = lv_img_create(ui_ContainerWifiSignal);
    lv_obj_set_width(ui_ImageWifiSignal, LV_SIZE_CONTENT);   /// 6
    lv_obj_set_height(ui_ImageWifiSignal, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_align(ui_ImageWifiSignal, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerBattery = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerBattery);
    lv_obj_set_width(ui_ContainerBattery, 28);
    lv_obj_set_height(ui_ContainerBattery, 13);
    lv_obj_set_x(ui_ContainerBattery, 51);
    lv_obj_set_y(ui_ContainerBattery, 0);
    lv_obj_set_align(ui_ContainerBattery, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerBattery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBattery = lv_img_create(ui_ContainerBattery);
    lv_img_set_src(ui_ImageBattery, &ui_img_images_batteryoutline_png);
    lv_obj_set_width(ui_ImageBattery, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_ImageBattery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(ui_ImageBattery, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarBattery = lv_bar_create(ui_ContainerBattery);
    lv_bar_set_value(ui_BarBattery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBattery, 21);
    lv_obj_set_height(ui_BarBattery, 9);
    lv_obj_set_x(ui_BarBattery, 2);
    lv_obj_set_y(ui_BarBattery, 0);
    lv_obj_set_align(ui_BarBattery, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBattery, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerLoadMain = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerLoadMain);
    lv_obj_set_width(ui_ContainerLoadMain, 800);
    lv_obj_set_height(ui_ContainerLoadMain, 433);
    lv_obj_set_x(ui_ContainerLoadMain, 0);
    lv_obj_set_y(ui_ContainerLoadMain, 47);
    lv_obj_set_align(ui_ContainerLoadMain, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLoadMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerLoadMain, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerLoadMain, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLoadMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoadProgress = lv_spinner_create(ui_ContainerLoadMain, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoadProgress, 348);
    lv_obj_set_height(ui_SpinnerLoadProgress, 348);
    lv_obj_set_x(ui_SpinnerLoadProgress, 226);
    lv_obj_set_y(ui_SpinnerLoadProgress, 21);
    lv_obj_clear_flag(ui_SpinnerLoadProgress, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerLoadProgress, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerLoadProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerLoadProgress, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_SpinnerLoadProgress, &ui_img_images_load_spinner_png,
                                 LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerLoading = lv_obj_create(ui_SpinnerLoadProgress);
    lv_obj_remove_style_all(ui_ContainerLoading);
    lv_obj_set_width(ui_ContainerLoading, 268);
    lv_obj_set_height(ui_ContainerLoading, 92);
    lv_obj_set_x(ui_ContainerLoading, 40);
    lv_obj_set_y(ui_ContainerLoading, 154);
    lv_obj_clear_flag(ui_ContainerLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadName = lv_obj_create(ui_ContainerLoading);
    lv_obj_remove_style_all(ui_ContainerLoadName);
    lv_obj_set_width(ui_ContainerLoadName, 268);
    lv_obj_set_height(ui_ContainerLoadName, 38);
    lv_obj_clear_flag(ui_ContainerLoadName, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLoadName = lv_img_create(ui_ContainerLoadName);
    lv_img_set_src(ui_ImageLoadName, &ui_img_images_load_en_us_png);
    lv_obj_set_width(ui_ImageLoadName, LV_SIZE_CONTENT);   /// 268
    lv_obj_set_height(ui_ImageLoadName, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_align(ui_ImageLoadName, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLoadName, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadName, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelLoading = lv_label_create(ui_SpinnerLoadProgress);
    lv_obj_set_width(ui_LabelLoading, 95);
    lv_obj_set_height(ui_LabelLoading, 25);
    lv_obj_set_x(ui_LabelLoading, 0);
    lv_obj_set_y(ui_LabelLoading, 62);
    lv_obj_set_align(ui_LabelLoading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoading, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoading, lv_color_hex(0x6C748B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLoading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoading, &ui_font_Poppins_Regular_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenLoadAQI, ui_event_ScreenLoadAQI, LV_EVENT_ALL, NULL);

}
