// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "../ui.h"

void ui_ScreenSettingAQI_screen_init(void)
{
    ui_ScreenSettingAQI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettingAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSettingAQI, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenSettingAQI, lv_color_hex(0x18191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettingAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSetting = lv_obj_create(ui_ScreenSettingAQI);
    lv_obj_remove_style_all(ui_ContainerSetting);
    lv_obj_set_width(ui_ContainerSetting, 800);
    lv_obj_set_height(ui_ContainerSetting, 480);
    lv_obj_set_align(ui_ContainerSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerSettingMain = lv_obj_create(ui_ContainerSetting);
    lv_obj_remove_style_all(ui_ContainerSettingMain);
    lv_obj_set_width(ui_ContainerSettingMain, 800);
    lv_obj_set_height(ui_ContainerSettingMain, 480);
    lv_obj_set_align(ui_ContainerSettingMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerSettingMain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerSettingMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerSettingTitle = lv_obj_create(ui_ContainerSettingMain);
    lv_obj_remove_style_all(ui_ContainerSettingTitle);
    lv_obj_set_width(ui_ContainerSettingTitle, LV_SIZE_CONTENT);   /// 736
    lv_obj_set_height(ui_ContainerSettingTitle, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_ContainerSettingTitle, 0);
    lv_obj_set_y(ui_ContainerSettingTitle, 47);
    lv_obj_set_align(ui_ContainerSettingTitle, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSettingTitle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerSettingTitleIcon = lv_obj_create(ui_ContainerSettingTitle);
    lv_obj_remove_style_all(ui_ContainerSettingTitleIcon);
    lv_obj_set_width(ui_ContainerSettingTitleIcon, 44);
    lv_obj_set_height(ui_ContainerSettingTitleIcon, 44);
    lv_obj_set_align(ui_ContainerSettingTitleIcon, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerSettingTitleIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSettingTitleIcon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSettingTitleIcon, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSettingTitleIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSettingTitleIcon = lv_img_create(ui_ContainerSettingTitleIcon);
    lv_img_set_src(ui_ImageSettingTitleIcon, &ui_img_images_wifi_44_png);
    lv_obj_set_width(ui_ImageSettingTitleIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingTitleIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSettingTitleIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSettingTitleIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingTitleIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettingTitleName = lv_label_create(ui_ContainerSettingTitle);
    lv_obj_set_width(ui_LabelSettingTitleName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingTitleName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettingTitleName, 56);
    lv_obj_set_y(ui_LabelSettingTitleName, 0);
    lv_obj_set_align(ui_LabelSettingTitleName, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSettingTitleName, "Wi-Fi Settings");
    lv_obj_set_style_text_font(ui_LabelSettingTitleName, &ui_font_Poppins_Light_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingButton = lv_obj_create(ui_ContainerSettingMain);
    lv_obj_remove_style_all(ui_ContainerSettingButton);
    lv_obj_set_width(ui_ContainerSettingButton, 448);
    lv_obj_set_height(ui_ContainerSettingButton, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_ContainerSettingButton, 0);
    lv_obj_set_y(ui_ContainerSettingButton, 390);
    lv_obj_set_align(ui_ContainerSettingButton, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSettingButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerSettingButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettingButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettingButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettingButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettingBack = lv_btn_create(ui_ContainerSettingButton);
    lv_obj_set_width(ui_ButtonSettingBack, 216);
    lv_obj_set_height(ui_ButtonSettingBack, 48);
    lv_obj_set_align(ui_ButtonSettingBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ButtonSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSettingBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSettingBack, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSettingBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSettingBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonSettingBack, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonSettingBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonSettingBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonSettingBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonSettingBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonSettingBack, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonSettingBack, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingBackButton = lv_label_create(ui_ButtonSettingBack);
    lv_obj_set_width(ui_LabelSettingBackButton, 39);
    lv_obj_set_height(ui_LabelSettingBackButton, 24);
    lv_obj_set_align(ui_LabelSettingBackButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettingBackButton, "Back");
    lv_obj_set_style_text_color(ui_LabelSettingBackButton, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingBackButton, &ui_font_Poppins_Regular_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettingNext = lv_btn_create(ui_ContainerSettingButton);
    lv_obj_set_width(ui_ButtonSettingNext, 216);
    lv_obj_set_height(ui_ButtonSettingNext, 48);
    lv_obj_set_align(ui_ButtonSettingNext, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonSettingNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSettingNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSettingNext, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSettingNext, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSettingNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonSettingNext, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonSettingNext, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonSettingNext, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonSettingNext, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingNextButton = lv_label_create(ui_ButtonSettingNext);
    lv_obj_set_width(ui_LabelSettingNextButton, 35);
    lv_obj_set_height(ui_LabelSettingNextButton, 24);
    lv_obj_set_align(ui_LabelSettingNextButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettingNextButton, "Next");
    lv_obj_set_style_text_font(ui_LabelSettingNextButton, &ui_font_Poppins_Regular_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingStage = lv_obj_create(ui_ContainerSettingMain);
    lv_obj_remove_style_all(ui_ContainerSettingStage);
    lv_obj_set_width(ui_ContainerSettingStage, 270);
    lv_obj_set_height(ui_ContainerSettingStage, LV_SIZE_CONTENT);    /// 6
    lv_obj_set_x(ui_ContainerSettingStage, 0);
    lv_obj_set_y(ui_ContainerSettingStage, 460);
    lv_obj_set_align(ui_ContainerSettingStage, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSettingStage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSettingStageLanguage = lv_img_create(ui_ContainerSettingStage);
    lv_img_set_src(ui_ImageSettingStageLanguage, &ui_img_images_stage_grey_png);
    lv_obj_set_width(ui_ImageSettingStageLanguage, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_ImageSettingStageLanguage, LV_SIZE_CONTENT);    /// 6
    lv_obj_set_align(ui_ImageSettingStageLanguage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageSettingStageLanguage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingStageLanguage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSettingStageCountry = lv_img_create(ui_ContainerSettingStage);
    lv_img_set_src(ui_ImageSettingStageCountry, &ui_img_images_stage_grey_png);
    lv_obj_set_width(ui_ImageSettingStageCountry, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_ImageSettingStageCountry, LV_SIZE_CONTENT);    /// 6
    lv_obj_set_align(ui_ImageSettingStageCountry, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageSettingStageCountry, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingStageCountry, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSettingStageWifi = lv_img_create(ui_ContainerSettingStage);
    lv_img_set_src(ui_ImageSettingStageWifi, &ui_img_images_stage_grey_png);
    lv_obj_set_width(ui_ImageSettingStageWifi, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_ImageSettingStageWifi, LV_SIZE_CONTENT);    /// 6
    lv_obj_set_align(ui_ImageSettingStageWifi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ImageSettingStageWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingStageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerSettingWifi = lv_obj_create(ui_ContainerSettingMain);
    lv_obj_remove_style_all(ui_ContainerSettingWifi);
    lv_obj_set_width(ui_ContainerSettingWifi, 800);
    lv_obj_set_height(ui_ContainerSettingWifi, 365);
    lv_obj_set_x(ui_ContainerSettingWifi, 0);
    lv_obj_set_y(ui_ContainerSettingWifi, 115);
    lv_obj_set_align(ui_ContainerSettingWifi, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSettingWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSettingWifi, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSettingWifi, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSettingWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSettingWifi, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettingWifi, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettingWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettingWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingWifiEnable = lv_obj_create(ui_ContainerSettingWifi);
    lv_obj_remove_style_all(ui_ContainerSettingWifiEnable);
    lv_obj_set_width(ui_ContainerSettingWifiEnable, 736);
    lv_obj_set_height(ui_ContainerSettingWifiEnable, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_ContainerSettingWifiEnable, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSettingWifiEnable, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSettingWifiEnable, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSettingWifiEnable, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSettingWifiEnable, 82, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSettingWifiEnable, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettingWifiEnable, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettingWifiEnable, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettingWifiEnable, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingWifiEnableIcon = lv_obj_create(ui_ContainerSettingWifiEnable);
    lv_obj_remove_style_all(ui_ContainerSettingWifiEnableIcon);
    lv_obj_set_width(ui_ContainerSettingWifiEnableIcon, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ContainerSettingWifiEnableIcon, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_align(ui_ContainerSettingWifiEnableIcon, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerSettingWifiEnableIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerSettingWifiEnableIcon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerSettingWifiEnableIcon, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSettingWifiEnableIcon, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSettingWifiEnableIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettingWifiEnableIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettingWifiEnableIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettingWifiEnableIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSettingWifiEnableIcon = lv_img_create(ui_ContainerSettingWifiEnableIcon);
    lv_img_set_src(ui_ImageSettingWifiEnableIcon, &ui_img_images_wifi_blue_24_png);
    lv_obj_set_width(ui_ImageSettingWifiEnableIcon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageSettingWifiEnableIcon, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_ImageSettingWifiEnableIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageSettingWifiEnableIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingWifiEnableIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettingWifiEnable = lv_label_create(ui_ContainerSettingWifiEnable);
    lv_obj_set_width(ui_LabelSettingWifiEnable, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_LabelSettingWifiEnable, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_LabelSettingWifiEnable, 56);
    lv_obj_set_y(ui_LabelSettingWifiEnable, 0);
    lv_obj_set_align(ui_LabelSettingWifiEnable, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSettingWifiEnable, "Wi-Fi");
    lv_obj_set_style_text_font(ui_LabelSettingWifiEnable, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchSettingWifiEnable = lv_switch_create(ui_ContainerSettingWifiEnable);
    lv_obj_set_width(ui_SwitchSettingWifiEnable, 67);
    lv_obj_set_height(ui_SwitchSettingWifiEnable, 35);
    lv_obj_set_align(ui_SwitchSettingWifiEnable, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_SwitchSettingWifiEnable, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_SwitchSettingWifiEnable, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchSettingWifiEnable, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ContainerWifiPassword = lv_obj_create(ui_ContainerSetting);
    lv_obj_remove_style_all(ui_ContainerWifiPassword);
    lv_obj_set_width(ui_ContainerWifiPassword, 800);
    lv_obj_set_height(ui_ContainerWifiPassword, 480);
    lv_obj_set_align(ui_ContainerWifiPassword, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerWifiPassword, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerWifiPassword, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerWifiPassword, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerWifiPassword, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerWifiPassword, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerWifiPassword, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWifiSelect = lv_obj_create(ui_ContainerWifiPassword);
    lv_obj_remove_style_all(ui_ContainerWifiSelect);
    lv_obj_set_width(ui_ContainerWifiSelect, 768);
    lv_obj_set_height(ui_ContainerWifiSelect, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_ContainerWifiSelect, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerWifiSelect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifiSelectIcon = lv_obj_create(ui_ContainerWifiSelect);
    lv_obj_remove_style_all(ui_ContainerWifiSelectIcon);
    lv_obj_set_width(ui_ContainerWifiSelectIcon, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ContainerWifiSelectIcon, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_align(ui_ContainerWifiSelectIcon, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerWifiSelectIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerWifiSelectIcon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerWifiSelectIcon, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerWifiSelectIcon, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerWifiSelectIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerWifiSelectIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerWifiSelectIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerWifiSelectIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifiSelectIcon = lv_img_create(ui_ContainerWifiSelectIcon);
    lv_img_set_src(ui_ImageWifiSelectIcon, &ui_img_images_wifi_blue_24_png);
    lv_obj_set_width(ui_ImageWifiSelectIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifiSelectIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWifiSelectIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageWifiSelectIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiSelectIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWifiSelectName = lv_label_create(ui_ContainerWifiSelect);
    lv_obj_set_width(ui_LabelWifiSelectName, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_LabelWifiSelectName, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_LabelWifiSelectName, 55);
    lv_obj_set_y(ui_LabelWifiSelectName, 0);
    lv_obj_set_align(ui_LabelWifiSelectName, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWifiSelectName, "Air Quality");
    lv_obj_set_style_text_font(ui_LabelWifiSelectName, &ui_font_Poppins_Regular_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifiSelectExit = lv_img_create(ui_ContainerWifiSelect);
    lv_img_set_src(ui_ImageWifiSelectExit, &ui_img_images_exit_png);
    lv_obj_set_width(ui_ImageWifiSelectExit, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageWifiSelectExit, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_ImageWifiSelectExit, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ImageWifiSelectExit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiSelectExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifiPasswordType = lv_obj_create(ui_ContainerWifiPassword);
    lv_obj_remove_style_all(ui_ContainerWifiPasswordType);
    lv_obj_set_width(ui_ContainerWifiPasswordType, 768);
    lv_obj_set_height(ui_ContainerWifiPasswordType, 56);
    lv_obj_set_x(ui_ContainerWifiPasswordType, 0);
    lv_obj_set_y(ui_ContainerWifiPasswordType, 60);
    lv_obj_set_align(ui_ContainerWifiPasswordType, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerWifiPasswordType, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerWifiPasswordType, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerWifiPasswordType, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerWifiPasswordType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerWifiPasswordType, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerWifiPasswordType, 26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerWifiPasswordType, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifiPasswordLock = lv_img_create(ui_ContainerWifiPasswordType);
    lv_img_set_src(ui_ImageWifiPasswordLock, &ui_img_images_wifi_lock_select_png);
    lv_obj_set_width(ui_ImageWifiPasswordLock, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageWifiPasswordLock, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_ImageWifiPasswordLock, 12);
    lv_obj_set_y(ui_ImageWifiPasswordLock, 0);
    lv_obj_set_align(ui_ImageWifiPasswordLock, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageWifiPasswordLock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiPasswordLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextWifiPasswordType = lv_textarea_create(ui_ContainerWifiPasswordType);
    lv_obj_set_width(ui_TextWifiPasswordType, 708);
    lv_obj_set_height(ui_TextWifiPasswordType, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_TextWifiPasswordType, -12);
    lv_obj_set_y(ui_TextWifiPasswordType, 0);
    lv_obj_set_align(ui_TextWifiPasswordType, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_TextWifiPasswordType, 64);
    lv_textarea_set_placeholder_text(ui_TextWifiPasswordType, "Enter password");
    lv_textarea_set_one_line(ui_TextWifiPasswordType, true);
    lv_textarea_set_password_mode(ui_TextWifiPasswordType, true);
    lv_obj_clear_flag(ui_TextWifiPasswordType, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextWifiPasswordType, &ui_font_Poppins_Light_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextWifiPasswordType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextWifiPasswordType, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextWifiPasswordType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextWifiPasswordType, &ui_font_Poppins_Light_18,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ButtonWifiConnect = lv_btn_create(ui_ContainerWifiPassword);
    lv_obj_set_width(ui_ButtonWifiConnect, 768);
    lv_obj_set_height(ui_ButtonWifiConnect, 48);
    lv_obj_set_x(ui_ButtonWifiConnect, 0);
    lv_obj_set_y(ui_ButtonWifiConnect, 132);
    lv_obj_set_align(ui_ButtonWifiConnect, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonWifiConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWifiConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonWifiConnect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWifiConnect, lv_color_hex(0x1F78E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonWifiConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonWifiConnect, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonWifiConnect, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonWifiConnect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonWifiConnect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWifiConnectButton = lv_label_create(ui_ButtonWifiConnect);
    lv_obj_set_width(ui_LabelWifiConnectButton, 69);
    lv_obj_set_height(ui_LabelWifiConnectButton, 24);
    lv_obj_set_align(ui_LabelWifiConnectButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWifiConnectButton, "Connect");
    lv_obj_set_style_text_font(ui_LabelWifiConnectButton, &ui_font_Poppins_Regular_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardWifiPassword = lv_keyboard_create(ui_ContainerWifiPassword);
    lv_obj_set_width(ui_KeyboardWifiPassword, 768);
    lv_obj_set_height(ui_KeyboardWifiPassword, 252);
    lv_obj_set_x(ui_KeyboardWifiPassword, 0);
    lv_obj_set_y(ui_KeyboardWifiPassword, 196);
    lv_obj_set_align(ui_KeyboardWifiPassword, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_KeyboardWifiPassword, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_KeyboardWifiPassword, ui_TextWifiPasswordType);

}
