// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "../ui.h"

static int loading_progress = 0;
static lv_timer_t * loading_timer = NULL;

static void loading_timer_cb(lv_timer_t * timer)
{
    loading_progress += 75;
    lv_bar_set_value(ui_BarLoading, loading_progress, LV_ANIM_OFF);

    if (loading_progress >= 1000)
    {
        lv_timer_del(loading_timer);
        loading_timer = NULL;
    }
}

void ui_ScreenLoadAQI_screen_init(void)
{
    ui_ScreenLoadAQI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoadAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenLoadAQI, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenLoadAQI, lv_color_hex(0x18191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLoadAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoad = lv_obj_create(ui_ScreenLoadAQI);
    lv_obj_remove_style_all(ui_ContainerLoad);
    lv_obj_set_width(ui_ContainerLoad, 800);
    lv_obj_set_height(ui_ContainerLoad, 480);
    lv_obj_set_align(ui_ContainerLoad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLoad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerStatus = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerStatus);
    lv_obj_set_width(ui_ContainerStatus, 800);
    lv_obj_set_height(ui_ContainerStatus, 47);
    lv_obj_set_align(ui_ContainerStatus, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContaierStatusLeft = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContaierStatusLeft);
    lv_obj_set_width(ui_ContaierStatusLeft, 54);
    lv_obj_set_height(ui_ContaierStatusLeft, 21);
    lv_obj_set_x(ui_ContaierStatusLeft, 32);
    lv_obj_set_y(ui_ContaierStatusLeft, 14);
    lv_obj_clear_flag(ui_ContaierStatusLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_ContaierStatusLeft);
    lv_obj_set_width(ui_LabelTime, 54);
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "9:41");
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerStatusCenter = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContainerStatusCenter);
    lv_obj_set_height(ui_ContainerStatusCenter, 34);
    lv_obj_set_width(ui_ContainerStatusCenter, LV_SIZE_CONTENT);   /// 99
    lv_obj_set_align(ui_ContainerStatusCenter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerStatusCenter, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerStatusCenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerStatusCenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerStatusCenter, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerStatusCenter, 82, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerStatusCenter, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerStatusCenter, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerStatusCenter, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerStatusCenter, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSetting = lv_img_create(ui_ContainerStatusCenter);
    lv_img_set_src(ui_ImageSetting, &ui_img_images_setting_png);
    lv_obj_set_width(ui_ImageSetting, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_ImageSetting, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_ImageSetting, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST |
                    LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSetting = lv_label_create(ui_ContainerStatusCenter);
    lv_obj_set_width(ui_LabelSetting, LV_SIZE_CONTENT);   /// 57
    lv_obj_set_height(ui_LabelSetting, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_LabelSetting, 24);
    lv_obj_set_y(ui_LabelSetting, 0);
    lv_obj_set_align(ui_LabelSetting, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSetting, "Settings");
    lv_obj_add_flag(ui_LabelSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_font(ui_LabelSetting, &ui_font_Poppins_Regular_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerStatusRight = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContainerStatusRight);
    lv_obj_set_width(ui_ContainerStatusRight, 79);
    lv_obj_set_height(ui_ContainerStatusRight, 13);
    lv_obj_set_x(ui_ContainerStatusRight, -32);
    lv_obj_set_y(ui_ContainerStatusRight, 19);
    lv_obj_set_align(ui_ContainerStatusRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ContainerStatusRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMobileSignal = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerMobileSignal);
    lv_obj_set_width(ui_ContainerMobileSignal, 18);
    lv_obj_set_height(ui_ContainerMobileSignal, 12);
    lv_obj_set_align(ui_ContainerMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerMobileSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMobileSignal = lv_img_create(ui_ContainerMobileSignal);
    lv_img_set_src(ui_ImageMobileSignal, &ui_img_images_mobilesignal_png);
    lv_obj_set_width(ui_ImageMobileSignal, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageMobileSignal, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_ImageMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifiSignal = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerWifiSignal);
    lv_obj_set_width(ui_ContainerWifiSignal, 17);
    lv_obj_set_height(ui_ContainerWifiSignal, 12);
    lv_obj_set_x(ui_ContainerWifiSignal, 26);
    lv_obj_set_y(ui_ContainerWifiSignal, 0);
    lv_obj_set_align(ui_ContainerWifiSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerWifiSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifiSignal = lv_img_create(ui_ContainerWifiSignal);
    lv_obj_set_width(ui_ImageWifiSignal, LV_SIZE_CONTENT);   /// 6
    lv_obj_set_height(ui_ImageWifiSignal, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_align(ui_ImageWifiSignal, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerBattery = lv_obj_create(ui_ContainerStatusRight);
    lv_obj_remove_style_all(ui_ContainerBattery);
    lv_obj_set_width(ui_ContainerBattery, 28);
    lv_obj_set_height(ui_ContainerBattery, 13);
    lv_obj_set_x(ui_ContainerBattery, 51);
    lv_obj_set_y(ui_ContainerBattery, 0);
    lv_obj_set_align(ui_ContainerBattery, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerBattery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBattery = lv_img_create(ui_ContainerBattery);
    lv_img_set_src(ui_ImageBattery, &ui_img_images_batteryoutline_png);
    lv_obj_set_width(ui_ImageBattery, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_ImageBattery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(ui_ImageBattery, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarBattery = lv_bar_create(ui_ContainerBattery);
    lv_bar_set_value(ui_BarBattery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBattery, 21);
    lv_obj_set_height(ui_BarBattery, 9);
    lv_obj_set_x(ui_BarBattery, 2);
    lv_obj_set_y(ui_BarBattery, 0);
    lv_obj_set_align(ui_BarBattery, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBattery, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerLoadMain = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerLoadMain);
    lv_obj_set_width(ui_ContainerLoadMain, 800);
    lv_obj_set_height(ui_ContainerLoadMain, 433);
    lv_obj_set_x(ui_ContainerLoadMain, 0);
    lv_obj_set_y(ui_ContainerLoadMain, 47);
    lv_obj_set_align(ui_ContainerLoadMain, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLoadMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerLoadMain, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerLoadMain, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLoadMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLoadLogo = lv_img_create(ui_ContainerLoadMain);
    lv_img_set_src(ui_ImageLoadLogo, &ui_img_images_load_en_us_png);
    lv_obj_set_width(ui_ImageLoadLogo, LV_SIZE_CONTENT);   /// 268
    lv_obj_set_height(ui_ImageLoadLogo, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_ImageLoadLogo, 0);
    lv_obj_set_y(ui_ImageLoadLogo, 150);
    lv_obj_set_align(ui_ImageLoadLogo, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageLoadLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarLoading = lv_bar_create(ui_ContainerLoadMain);
    lv_bar_set_range(ui_BarLoading, 0, 1000);
    lv_obj_set_width(ui_BarLoading, 700);
    lv_obj_set_height(ui_BarLoading, 25);
    lv_obj_set_x(ui_BarLoading, 0);
    lv_obj_set_y(ui_BarLoading, 220);
    lv_obj_set_align(ui_BarLoading, LV_ALIGN_TOP_MID);

    ui_LabelLoading = lv_label_create(ui_BarLoading);
    lv_obj_set_width(ui_LabelLoading, 95);
    lv_obj_set_height(ui_LabelLoading, 25);
    lv_obj_set_align(ui_LabelLoading, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelLoading, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoading, lv_color_hex(0x6C748B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLoading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoading, &ui_font_Poppins_Regular_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenLoadAQI, ui_event_ScreenLoadAQI, LV_EVENT_ALL, NULL);

    // Create timer to update loading bar every 10ms for 1 second total
    loading_timer = lv_timer_create(loading_timer_cb, 1, NULL);
}
