// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "../ui.h"

void ui_ScreenIndicatorAQI_screen_init(void)
{
    ui_ScreenIndicatorAQI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenIndicatorAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenIndicatorAQI, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenIndicatorAQI, lv_color_hex(0x18191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenIndicatorAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRegionLeft = lv_obj_create(ui_ScreenIndicatorAQI);
    lv_obj_remove_style_all(ui_ContainerRegionLeft);
    lv_obj_set_width(ui_ContainerRegionLeft, 212);
    lv_obj_set_height(ui_ContainerRegionLeft, 480);
    lv_obj_set_align(ui_ContainerRegionLeft, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerRegionLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerRegionLeft, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerRegionLeft, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerRegionLeft, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerRegionLeft, 32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverPM1 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerCoverPM1);
    lv_obj_set_width(ui_ContainerCoverPM1, 212);
    lv_obj_set_height(ui_ContainerCoverPM1, 133);
    lv_obj_set_x(ui_ContainerCoverPM1, 0);
    lv_obj_set_y(ui_ContainerCoverPM1, -32);
    lv_obj_set_align(ui_ContainerCoverPM1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverPM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverPM1, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPM1 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_set_width(ui_PanelPM1, 164);
    lv_obj_set_height(ui_PanelPM1, 92);
    lv_obj_set_align(ui_PanelPM1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPM1, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPM1, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPM1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPM1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPM1 = lv_obj_create(ui_PanelPM1);
    lv_obj_remove_style_all(ui_ContainerPM1);
    lv_obj_set_width(ui_ContainerPM1, 164);
    lv_obj_set_height(ui_ContainerPM1, 68);
    lv_obj_set_align(ui_ContainerPM1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPM1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconPM1 = lv_img_create(ui_ContainerPM1);
    lv_img_set_src(ui_ImageIconPM1, &ui_img_images_pm_white_png);
    lv_obj_set_width(ui_ImageIconPM1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconPM1, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconPM1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconPM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataPM1 = lv_obj_create(ui_ContainerPM1);
    lv_obj_remove_style_all(ui_ContainerDataPM1);
    lv_obj_set_width(ui_ContainerDataPM1, 128);
    lv_obj_set_height(ui_ContainerDataPM1, 68);
    lv_obj_set_x(ui_ContainerDataPM1, 36);
    lv_obj_set_y(ui_ContainerDataPM1, 0);
    lv_obj_set_align(ui_ContainerDataPM1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataPM1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataPM1 = lv_obj_create(ui_ContainerDataPM1);
    lv_obj_remove_style_all(ui_ContainerLabelDataPM1);
    lv_obj_set_height(ui_ContainerLabelDataPM1, 28);
    lv_obj_set_width(ui_ContainerLabelDataPM1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataPM1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataPM1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValuePM1 = lv_label_create(ui_ContainerLabelDataPM1);
    lv_obj_set_width(ui_LabelValuePM1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValuePM1, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValuePM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValuePM1, "0");
    lv_obj_set_style_text_align(ui_LabelValuePM1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValuePM1, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitPM1 = lv_label_create(ui_ContainerLabelDataPM1);
    lv_obj_set_width(ui_LabelUnitPM1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitPM1, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitPM1, "µg/m³");
    lv_obj_set_style_text_align(ui_LabelUnitPM1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitPM1, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValuePM1 = lv_bar_create(ui_ContainerDataPM1);
    lv_bar_set_range(ui_BarValuePM1, 0, 500);
    lv_obj_set_width(ui_BarValuePM1, 128);
    lv_obj_set_height(ui_BarValuePM1, 4);
    lv_obj_set_x(ui_BarValuePM1, 0);
    lv_obj_set_y(ui_BarValuePM1, 36);
    lv_obj_set_align(ui_BarValuePM1, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValuePM1, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValuePM1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNamePM1 = lv_label_create(ui_ContainerDataPM1);
    lv_obj_set_height(ui_LabelNamePM1, 20);
    lv_obj_set_width(ui_LabelNamePM1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNamePM1, 0);
    lv_obj_set_y(ui_LabelNamePM1, 48);
    lv_obj_set_align(ui_LabelNamePM1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNamePM1, "PM₁");
    lv_obj_set_style_text_align(ui_LabelNamePM1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNamePM1, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLinePM1 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerLinePM1);
    lv_obj_set_width(ui_ContainerLinePM1, 162);
    lv_obj_set_height(ui_ContainerLinePM1, 1);
    lv_obj_set_x(ui_ContainerLinePM1, 0);
    lv_obj_set_y(ui_ContainerLinePM1, 100);
    lv_obj_set_align(ui_ContainerLinePM1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLinePM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLinePM1, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLinePM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverPM25 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerCoverPM25);
    lv_obj_set_width(ui_ContainerCoverPM25, 212);
    lv_obj_set_height(ui_ContainerCoverPM25, 112);
    lv_obj_set_x(ui_ContainerCoverPM25, 0);
    lv_obj_set_y(ui_ContainerCoverPM25, 99);
    lv_obj_set_align(ui_ContainerCoverPM25, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverPM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverPM25, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPM25 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_set_width(ui_PanelPM25, 164);
    lv_obj_set_height(ui_PanelPM25, 92);
    lv_obj_set_x(ui_PanelPM25, 0);
    lv_obj_set_y(ui_PanelPM25, 109);
    lv_obj_set_align(ui_PanelPM25, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPM25, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPM25, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPM25, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPM25, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPM25 = lv_obj_create(ui_PanelPM25);
    lv_obj_remove_style_all(ui_ContainerPM25);
    lv_obj_set_width(ui_ContainerPM25, 164);
    lv_obj_set_height(ui_ContainerPM25, 68);
    lv_obj_set_align(ui_ContainerPM25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPM25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconPM25 = lv_img_create(ui_ContainerPM25);
    lv_img_set_src(ui_ImageIconPM25, &ui_img_images_pm_white_png);
    lv_obj_set_width(ui_ImageIconPM25, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconPM25, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconPM25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconPM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataPM25 = lv_obj_create(ui_ContainerPM25);
    lv_obj_remove_style_all(ui_ContainerDataPM25);
    lv_obj_set_width(ui_ContainerDataPM25, 128);
    lv_obj_set_height(ui_ContainerDataPM25, 68);
    lv_obj_set_x(ui_ContainerDataPM25, 36);
    lv_obj_set_y(ui_ContainerDataPM25, 0);
    lv_obj_set_align(ui_ContainerDataPM25, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataPM25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataPM25 = lv_obj_create(ui_ContainerDataPM25);
    lv_obj_remove_style_all(ui_ContainerLabelDataPM25);
    lv_obj_set_height(ui_ContainerLabelDataPM25, 28);
    lv_obj_set_width(ui_ContainerLabelDataPM25, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataPM25, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataPM25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValuePM25 = lv_label_create(ui_ContainerLabelDataPM25);
    lv_obj_set_width(ui_LabelValuePM25, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValuePM25, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValuePM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValuePM25, "0");
    lv_obj_set_style_text_align(ui_LabelValuePM25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValuePM25, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitPM25 = lv_label_create(ui_ContainerLabelDataPM25);
    lv_obj_set_width(ui_LabelUnitPM25, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitPM25, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitPM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitPM25, "µg/m³");
    lv_obj_set_style_text_align(ui_LabelUnitPM25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitPM25, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValuePM25 = lv_bar_create(ui_ContainerDataPM25);
    lv_bar_set_range(ui_BarValuePM25, 0, 1000);
    lv_obj_set_width(ui_BarValuePM25, 128);
    lv_obj_set_height(ui_BarValuePM25, 4);
    lv_obj_set_x(ui_BarValuePM25, 0);
    lv_obj_set_y(ui_BarValuePM25, 36);
    lv_obj_set_align(ui_BarValuePM25, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValuePM25, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValuePM25, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNamePM25 = lv_label_create(ui_ContainerDataPM25);
    lv_obj_set_height(ui_LabelNamePM25, 20);
    lv_obj_set_width(ui_LabelNamePM25, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNamePM25, 0);
    lv_obj_set_y(ui_LabelNamePM25, 48);
    lv_obj_set_align(ui_LabelNamePM25, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNamePM25, "PM₂.₅");
    lv_obj_set_style_text_align(ui_LabelNamePM25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNamePM25, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLinePM25 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerLinePM25);
    lv_obj_set_width(ui_ContainerLinePM25, 162);
    lv_obj_set_height(ui_ContainerLinePM25, 1);
    lv_obj_set_x(ui_ContainerLinePM25, 0);
    lv_obj_set_y(ui_ContainerLinePM25, 209);
    lv_obj_set_align(ui_ContainerLinePM25, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLinePM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLinePM25, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLinePM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverPM10 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerCoverPM10);
    lv_obj_set_width(ui_ContainerCoverPM10, 212);
    lv_obj_set_height(ui_ContainerCoverPM10, 112);
    lv_obj_set_x(ui_ContainerCoverPM10, 0);
    lv_obj_set_y(ui_ContainerCoverPM10, 208);
    lv_obj_set_align(ui_ContainerCoverPM10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverPM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverPM10, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPM10 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_set_width(ui_PanelPM10, 164);
    lv_obj_set_height(ui_PanelPM10, 92);
    lv_obj_set_x(ui_PanelPM10, 0);
    lv_obj_set_y(ui_PanelPM10, 218);
    lv_obj_set_align(ui_PanelPM10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPM10, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPM10, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPM10, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPM10, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPM10 = lv_obj_create(ui_PanelPM10);
    lv_obj_remove_style_all(ui_ContainerPM10);
    lv_obj_set_width(ui_ContainerPM10, 164);
    lv_obj_set_height(ui_ContainerPM10, 68);
    lv_obj_set_align(ui_ContainerPM10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPM10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconPM10 = lv_img_create(ui_ContainerPM10);
    lv_img_set_src(ui_ImageIconPM10, &ui_img_images_pm_white_png);
    lv_obj_set_width(ui_ImageIconPM10, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconPM10, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconPM10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconPM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataPM10 = lv_obj_create(ui_ContainerPM10);
    lv_obj_remove_style_all(ui_ContainerDataPM10);
    lv_obj_set_width(ui_ContainerDataPM10, 128);
    lv_obj_set_height(ui_ContainerDataPM10, 68);
    lv_obj_set_x(ui_ContainerDataPM10, 36);
    lv_obj_set_y(ui_ContainerDataPM10, 0);
    lv_obj_set_align(ui_ContainerDataPM10, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataPM10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataPM10 = lv_obj_create(ui_ContainerDataPM10);
    lv_obj_remove_style_all(ui_ContainerLabelDataPM10);
    lv_obj_set_height(ui_ContainerLabelDataPM10, 28);
    lv_obj_set_width(ui_ContainerLabelDataPM10, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataPM10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataPM10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValuePM10 = lv_label_create(ui_ContainerLabelDataPM10);
    lv_obj_set_width(ui_LabelValuePM10, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValuePM10, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValuePM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValuePM10, "0");
    lv_obj_set_style_text_align(ui_LabelValuePM10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValuePM10, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitPM10 = lv_label_create(ui_ContainerLabelDataPM10);
    lv_obj_set_width(ui_LabelUnitPM10, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitPM10, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitPM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitPM10, "µg/m³");
    lv_obj_set_style_text_align(ui_LabelUnitPM10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitPM10, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValuePM10 = lv_bar_create(ui_ContainerDataPM10);
    lv_bar_set_range(ui_BarValuePM10, 0, 1500);
    lv_obj_set_width(ui_BarValuePM10, 128);
    lv_obj_set_height(ui_BarValuePM10, 4);
    lv_obj_set_x(ui_BarValuePM10, 0);
    lv_obj_set_y(ui_BarValuePM10, 36);
    lv_obj_set_align(ui_BarValuePM10, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValuePM10, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValuePM10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNamePM10 = lv_label_create(ui_ContainerDataPM10);
    lv_obj_set_height(ui_LabelNamePM10, 20);
    lv_obj_set_width(ui_LabelNamePM10, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNamePM10, 0);
    lv_obj_set_y(ui_LabelNamePM10, 48);
    lv_obj_set_align(ui_LabelNamePM10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNamePM10, "PM₁₀");
    lv_obj_set_style_text_align(ui_LabelNamePM10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNamePM10, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLinePM10 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerLinePM10);
    lv_obj_set_width(ui_ContainerLinePM10, 162);
    lv_obj_set_height(ui_ContainerLinePM10, 1);
    lv_obj_set_x(ui_ContainerLinePM10, 0);
    lv_obj_set_y(ui_ContainerLinePM10, 318);
    lv_obj_set_align(ui_ContainerLinePM10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLinePM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLinePM10, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLinePM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverCO2 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_remove_style_all(ui_ContainerCoverCO2);
    lv_obj_set_width(ui_ContainerCoverCO2, 212);
    lv_obj_set_height(ui_ContainerCoverCO2, 131);
    lv_obj_set_x(ui_ContainerCoverCO2, 0);
    lv_obj_set_y(ui_ContainerCoverCO2, 317);
    lv_obj_set_align(ui_ContainerCoverCO2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverCO2, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCO2 = lv_obj_create(ui_ContainerRegionLeft);
    lv_obj_set_width(ui_PanelCO2, 164);
    lv_obj_set_height(ui_PanelCO2, 92);
    lv_obj_set_x(ui_PanelCO2, 0);
    lv_obj_set_y(ui_PanelCO2, 327);
    lv_obj_set_align(ui_PanelCO2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCO2, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCO2, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCO2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCO2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCO2 = lv_obj_create(ui_PanelCO2);
    lv_obj_remove_style_all(ui_ContainerCO2);
    lv_obj_set_width(ui_ContainerCO2, 164);
    lv_obj_set_height(ui_ContainerCO2, 68);
    lv_obj_set_align(ui_ContainerCO2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerCO2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconCO2 = lv_img_create(ui_ContainerCO2);
    lv_img_set_src(ui_ImageIconCO2, &ui_img_images_co2_white_png);
    lv_obj_set_width(ui_ImageIconCO2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconCO2, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconCO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataCO2 = lv_obj_create(ui_ContainerCO2);
    lv_obj_remove_style_all(ui_ContainerDataCO2);
    lv_obj_set_width(ui_ContainerDataCO2, 128);
    lv_obj_set_height(ui_ContainerDataCO2, 68);
    lv_obj_set_x(ui_ContainerDataCO2, 36);
    lv_obj_set_y(ui_ContainerDataCO2, 0);
    lv_obj_set_align(ui_ContainerDataCO2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataCO2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataCO2 = lv_obj_create(ui_ContainerDataCO2);
    lv_obj_remove_style_all(ui_ContainerLabelDataCO2);
    lv_obj_set_height(ui_ContainerLabelDataCO2, 28);
    lv_obj_set_width(ui_ContainerLabelDataCO2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataCO2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataCO2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValueCO2 = lv_label_create(ui_ContainerLabelDataCO2);
    lv_obj_set_width(ui_LabelValueCO2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValueCO2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValueCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueCO2, "0");
    lv_obj_set_style_text_align(ui_LabelValueCO2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueCO2, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitCO2 = lv_label_create(ui_ContainerLabelDataCO2);
    lv_obj_set_width(ui_LabelUnitCO2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitCO2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitCO2, "ppm");
    lv_obj_set_style_text_align(ui_LabelUnitCO2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitCO2, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValueCO2 = lv_bar_create(ui_ContainerDataCO2);
    lv_bar_set_range(ui_BarValueCO2, 400, 65000);
    lv_bar_set_value(ui_BarValueCO2, 400, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarValueCO2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarValueCO2, 128);
    lv_obj_set_height(ui_BarValueCO2, 4);
    lv_obj_set_x(ui_BarValueCO2, 0);
    lv_obj_set_y(ui_BarValueCO2, 36);
    lv_obj_set_align(ui_BarValueCO2, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValueCO2, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValueCO2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNameCO2 = lv_label_create(ui_ContainerDataCO2);
    lv_obj_set_height(ui_LabelNameCO2, 20);
    lv_obj_set_width(ui_LabelNameCO2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNameCO2, 0);
    lv_obj_set_y(ui_LabelNameCO2, 48);
    lv_obj_set_align(ui_LabelNameCO2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNameCO2, "CO₂");
    lv_obj_set_style_text_align(ui_LabelNameCO2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameCO2, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLineCenterLeft = lv_obj_create(ui_ScreenIndicatorAQI);
    lv_obj_set_width(ui_PanelLineCenterLeft, 1);
    lv_obj_set_height(ui_PanelLineCenterLeft, 480);
    lv_obj_set_x(ui_PanelLineCenterLeft, 212);
    lv_obj_set_y(ui_PanelLineCenterLeft, 0);
    lv_obj_set_align(ui_PanelLineCenterLeft, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelLineCenterLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLineCenterLeft, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLineCenterLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRegionCenter = lv_obj_create(ui_ScreenIndicatorAQI);
    lv_obj_remove_style_all(ui_ContainerRegionCenter);
    lv_obj_set_width(ui_ContainerRegionCenter, 374);
    lv_obj_set_height(ui_ContainerRegionCenter, 480);
    lv_obj_set_x(ui_ContainerRegionCenter, 213);
    lv_obj_set_y(ui_ContainerRegionCenter, 0);
    lv_obj_set_align(ui_ContainerRegionCenter, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerRegionCenter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerStatus = lv_obj_create(ui_ContainerRegionCenter);
    lv_obj_remove_style_all(ui_ContainerStatus);
    lv_obj_set_width(ui_ContainerStatus, 374);
    lv_obj_set_height(ui_ContainerStatus, 47);
    lv_obj_set_align(ui_ContainerStatus, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContaierLeftSide = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContaierLeftSide);
    lv_obj_set_width(ui_ContaierLeftSide, 54);
    lv_obj_set_height(ui_ContaierLeftSide, 21);
    lv_obj_set_x(ui_ContaierLeftSide, 24);
    lv_obj_set_y(ui_ContaierLeftSide, 14);
    lv_obj_clear_flag(ui_ContaierLeftSide, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_ContaierLeftSide);
    lv_obj_set_width(ui_LabelTime, 54);
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "9:41");
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRightSide = lv_obj_create(ui_ContainerStatus);
    lv_obj_remove_style_all(ui_ContainerRightSide);
    lv_obj_set_width(ui_ContainerRightSide, 79);
    lv_obj_set_height(ui_ContainerRightSide, 13);
    lv_obj_set_x(ui_ContainerRightSide, -24);
    lv_obj_set_y(ui_ContainerRightSide, 19);
    lv_obj_set_align(ui_ContainerRightSide, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ContainerRightSide, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMobileSignal = lv_obj_create(ui_ContainerRightSide);
    lv_obj_remove_style_all(ui_ContainerMobileSignal);
    lv_obj_set_width(ui_ContainerMobileSignal, 18);
    lv_obj_set_height(ui_ContainerMobileSignal, 12);
    lv_obj_set_align(ui_ContainerMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerMobileSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMobileSignal = lv_img_create(ui_ContainerMobileSignal);
    lv_img_set_src(ui_ImageMobileSignal, &ui_img_images_mobilesignal4_png);
    lv_obj_set_width(ui_ImageMobileSignal, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageMobileSignal, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_ImageMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMobileSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifi = lv_obj_create(ui_ContainerRightSide);
    lv_obj_remove_style_all(ui_ContainerWifi);
    lv_obj_set_width(ui_ContainerWifi, 17);
    lv_obj_set_height(ui_ContainerWifi, 12);
    lv_obj_set_x(ui_ContainerWifi, 26);
    lv_obj_set_y(ui_ContainerWifi, 0);
    lv_obj_set_align(ui_ContainerWifi, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi = lv_img_create(ui_ContainerWifi);
    lv_img_set_src(ui_ImageWifi, &ui_img_images_wifi3_png);
    lv_obj_set_width(ui_ImageWifi, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_ImageWifi, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_ImageWifi, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerBattery = lv_obj_create(ui_ContainerRightSide);
    lv_obj_remove_style_all(ui_ContainerBattery);
    lv_obj_set_width(ui_ContainerBattery, 28);
    lv_obj_set_height(ui_ContainerBattery, 13);
    lv_obj_set_x(ui_ContainerBattery, 51);
    lv_obj_set_y(ui_ContainerBattery, 0);
    lv_obj_set_align(ui_ContainerBattery, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerBattery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBattery = lv_img_create(ui_ContainerBattery);
    lv_img_set_src(ui_ImageBattery, &ui_img_images_batteryoutline_png);
    lv_obj_set_width(ui_ImageBattery, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_ImageBattery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(ui_ImageBattery, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarBattery = lv_bar_create(ui_ContainerBattery);
    lv_bar_set_value(ui_BarBattery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBattery, 21);
    lv_obj_set_height(ui_BarBattery, 9);
    lv_obj_set_x(ui_BarBattery, 2);
    lv_obj_set_y(ui_BarBattery, 0);
    lv_obj_set_align(ui_BarBattery, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBattery, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerMain = lv_obj_create(ui_ContainerRegionCenter);
    lv_obj_remove_style_all(ui_ContainerMain);
    lv_obj_set_width(ui_ContainerMain, 374);
    lv_obj_set_height(ui_ContainerMain, 427);
    lv_obj_set_x(ui_ContainerMain, 0);
    lv_obj_set_y(ui_ContainerMain, 53);
    lv_obj_set_align(ui_ContainerMain, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerMain, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerMain, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSelectAQI = lv_obj_create(ui_ContainerMain);
    lv_obj_remove_style_all(ui_ContainerSelectAQI);
    lv_obj_set_width(ui_ContainerSelectAQI, 373);
    lv_obj_set_height(ui_ContainerSelectAQI, 172);
    lv_obj_set_x(ui_ContainerSelectAQI, 0);
    lv_obj_set_y(ui_ContainerSelectAQI, 122);
    lv_obj_set_align(ui_ContainerSelectAQI, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerSelectAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ContainerSelectAQI, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContainerSelectAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueSelectAQI = lv_label_create(ui_ContainerSelectAQI);
    lv_obj_set_width(ui_LabelValueSelectAQI, 373);
    lv_obj_set_height(ui_LabelValueSelectAQI, 130);
    lv_obj_set_x(ui_LabelValueSelectAQI, 0);
    lv_obj_set_y(ui_LabelValueSelectAQI, -24);
    lv_obj_set_align(ui_LabelValueSelectAQI, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelValueSelectAQI, "0");
    lv_obj_set_style_text_color(ui_LabelValueSelectAQI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueSelectAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelValueSelectAQI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueSelectAQI, &ui_font_Poppins_ExtraLight_116, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContaierInforSelectAQI = lv_obj_create(ui_ContainerSelectAQI);
    lv_obj_remove_style_all(ui_ContaierInforSelectAQI);
    lv_obj_set_width(ui_ContaierInforSelectAQI, 373);
    lv_obj_set_height(ui_ContaierInforSelectAQI, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_ContaierInforSelectAQI, 0);
    lv_obj_set_y(ui_ContaierInforSelectAQI, 112);
    lv_obj_set_align(ui_ContaierInforSelectAQI, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContaierInforSelectAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLevelSelectAQI = lv_obj_create(ui_ContaierInforSelectAQI);
    lv_obj_remove_style_all(ui_ContainerLevelSelectAQI);
    lv_obj_set_width(ui_ContainerLevelSelectAQI, 373);
    lv_obj_set_height(ui_ContainerLevelSelectAQI, 30);
    lv_obj_set_align(ui_ContainerLevelSelectAQI, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLevelSelectAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerAlignLevelSelectAQI = lv_obj_create(ui_ContainerLevelSelectAQI);
    lv_obj_remove_style_all(ui_ContainerAlignLevelSelectAQI);
    lv_obj_set_height(ui_ContainerAlignLevelSelectAQI, 30);
    lv_obj_set_width(ui_ContainerAlignLevelSelectAQI, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_ContainerAlignLevelSelectAQI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAlignLevelSelectAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLevelSelectAQI = lv_img_create(ui_ContainerAlignLevelSelectAQI);
    lv_img_set_src(ui_ImageLevelSelectAQI, &ui_img_images_pm_white_png);
    lv_obj_set_width(ui_ImageLevelSelectAQI, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageLevelSelectAQI, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageLevelSelectAQI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLevelSelectAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUnitSelectAQI = lv_label_create(ui_ContainerAlignLevelSelectAQI);
    lv_obj_set_height(ui_LabelUnitSelectAQI, 30);
    lv_obj_set_width(ui_LabelUnitSelectAQI, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_LabelUnitSelectAQI, 32);
    lv_obj_set_y(ui_LabelUnitSelectAQI, 0);
    lv_label_set_text(ui_LabelUnitSelectAQI, "µg/m³");
    lv_obj_set_style_text_color(ui_LabelUnitSelectAQI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnitSelectAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelUnitSelectAQI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitSelectAQI, &ui_font_Poppins_Light_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerNameSelectAQI = lv_obj_create(ui_ContaierInforSelectAQI);
    lv_obj_remove_style_all(ui_ContainerNameSelectAQI);
    lv_obj_set_width(ui_ContainerNameSelectAQI, 373);
    lv_obj_set_height(ui_ContainerNameSelectAQI, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_ContainerNameSelectAQI, 0);
    lv_obj_set_y(ui_ContainerNameSelectAQI, 38);
    lv_obj_set_align(ui_ContainerNameSelectAQI, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerNameSelectAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNameSelectAQI = lv_label_create(ui_ContainerNameSelectAQI);
    lv_obj_set_height(ui_LabelNameSelectAQI, 24);
    lv_obj_set_width(ui_LabelNameSelectAQI, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_LabelNameSelectAQI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNameSelectAQI, "PM₁");
    lv_obj_set_style_text_color(ui_LabelNameSelectAQI, lv_color_hex(0xB4B9C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameSelectAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNameSelectAQI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameSelectAQI, &ui_font_OpenSans_Regular_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLineCenterRight = lv_obj_create(ui_ScreenIndicatorAQI);
    lv_obj_set_width(ui_PanelLineCenterRight, 1);
    lv_obj_set_height(ui_PanelLineCenterRight, 480);
    lv_obj_set_x(ui_PanelLineCenterRight, 587);
    lv_obj_set_y(ui_PanelLineCenterRight, 0);
    lv_obj_set_align(ui_PanelLineCenterRight, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelLineCenterRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLineCenterRight, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLineCenterRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRegionRight = lv_obj_create(ui_ScreenIndicatorAQI);
    lv_obj_remove_style_all(ui_ContainerRegionRight);
    lv_obj_set_width(ui_ContainerRegionRight, 212);
    lv_obj_set_height(ui_ContainerRegionRight, 480);
    lv_obj_set_x(ui_ContainerRegionRight, 588);
    lv_obj_set_y(ui_ContainerRegionRight, 0);
    lv_obj_set_align(ui_ContainerRegionRight, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerRegionRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerRegionRight, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerRegionRight, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerRegionRight, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerRegionRight, 32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverTEMP = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerCoverTEMP);
    lv_obj_set_width(ui_ContainerCoverTEMP, 212);
    lv_obj_set_height(ui_ContainerCoverTEMP, 133);
    lv_obj_set_x(ui_ContainerCoverTEMP, 0);
    lv_obj_set_y(ui_ContainerCoverTEMP, -32);
    lv_obj_set_align(ui_ContainerCoverTEMP, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverTEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverTEMP, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ContainerCoverTEMP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTEMP = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_set_width(ui_PanelTEMP, 164);
    lv_obj_set_height(ui_PanelTEMP, 92);
    lv_obj_set_align(ui_PanelTEMP, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTEMP, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTEMP, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTEMP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTEMP, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTEMP, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTEMP = lv_obj_create(ui_PanelTEMP);
    lv_obj_remove_style_all(ui_ContainerTEMP);
    lv_obj_set_width(ui_ContainerTEMP, 164);
    lv_obj_set_height(ui_ContainerTEMP, 68);
    lv_obj_set_align(ui_ContainerTEMP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconTEMP = lv_img_create(ui_ContainerTEMP);
    lv_img_set_src(ui_ImageIconTEMP, &ui_img_images_temp_white_png);
    lv_obj_set_width(ui_ImageIconTEMP, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconTEMP, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconTEMP, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconTEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataTEMP = lv_obj_create(ui_ContainerTEMP);
    lv_obj_remove_style_all(ui_ContainerDataTEMP);
    lv_obj_set_width(ui_ContainerDataTEMP, 128);
    lv_obj_set_height(ui_ContainerDataTEMP, 68);
    lv_obj_set_x(ui_ContainerDataTEMP, 36);
    lv_obj_set_y(ui_ContainerDataTEMP, 0);
    lv_obj_set_align(ui_ContainerDataTEMP, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataTEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataTEMP = lv_obj_create(ui_ContainerDataTEMP);
    lv_obj_remove_style_all(ui_ContainerLabelDataTEMP);
    lv_obj_set_height(ui_ContainerLabelDataTEMP, 28);
    lv_obj_set_width(ui_ContainerLabelDataTEMP, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataTEMP, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataTEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValueTEMP = lv_label_create(ui_ContainerLabelDataTEMP);
    lv_obj_set_width(ui_LabelValueTEMP, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValueTEMP, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValueTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueTEMP, "0");
    lv_obj_set_style_text_align(ui_LabelValueTEMP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueTEMP, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitTEMP = lv_label_create(ui_ContainerLabelDataTEMP);
    lv_obj_set_width(ui_LabelUnitTEMP, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitTEMP, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitTEMP, "°C");
    lv_obj_set_style_text_align(ui_LabelUnitTEMP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitTEMP, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValueTEMP = lv_bar_create(ui_ContainerDataTEMP);
    lv_bar_set_range(ui_BarValueTEMP, 0, 50);
    lv_obj_set_width(ui_BarValueTEMP, 128);
    lv_obj_set_height(ui_BarValueTEMP, 4);
    lv_obj_set_x(ui_BarValueTEMP, 0);
    lv_obj_set_y(ui_BarValueTEMP, 36);
    lv_obj_set_align(ui_BarValueTEMP, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValueTEMP, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValueTEMP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNameTEMP = lv_label_create(ui_ContainerDataTEMP);
    lv_obj_set_height(ui_LabelNameTEMP, 20);
    lv_obj_set_width(ui_LabelNameTEMP, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNameTEMP, 0);
    lv_obj_set_y(ui_LabelNameTEMP, 48);
    lv_obj_set_align(ui_LabelNameTEMP, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNameTEMP, "TEMP");
    lv_obj_set_style_text_align(ui_LabelNameTEMP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameTEMP, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLineTEMP = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerLineTEMP);
    lv_obj_set_width(ui_ContainerLineTEMP, 162);
    lv_obj_set_height(ui_ContainerLineTEMP, 1);
    lv_obj_set_x(ui_ContainerLineTEMP, 0);
    lv_obj_set_y(ui_ContainerLineTEMP, 100);
    lv_obj_set_align(ui_ContainerLineTEMP, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLineTEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLineTEMP, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLineTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverRH = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerCoverRH);
    lv_obj_set_width(ui_ContainerCoverRH, 212);
    lv_obj_set_height(ui_ContainerCoverRH, 112);
    lv_obj_set_x(ui_ContainerCoverRH, 0);
    lv_obj_set_y(ui_ContainerCoverRH, 99);
    lv_obj_set_align(ui_ContainerCoverRH, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverRH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverRH, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRH = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_set_width(ui_PanelRH, 164);
    lv_obj_set_height(ui_PanelRH, 92);
    lv_obj_set_x(ui_PanelRH, 0);
    lv_obj_set_y(ui_PanelRH, 109);
    lv_obj_set_align(ui_PanelRH, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelRH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelRH, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRH, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRH, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRH, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRH = lv_obj_create(ui_PanelRH);
    lv_obj_remove_style_all(ui_ContainerRH);
    lv_obj_set_width(ui_ContainerRH, 164);
    lv_obj_set_height(ui_ContainerRH, 68);
    lv_obj_set_align(ui_ContainerRH, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerRH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconRH = lv_img_create(ui_ContainerRH);
    lv_img_set_src(ui_ImageIconRH, &ui_img_images_rh_white_png);
    lv_obj_set_width(ui_ImageIconRH, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconRH, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconRH, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconRH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataRH = lv_obj_create(ui_ContainerRH);
    lv_obj_remove_style_all(ui_ContainerDataRH);
    lv_obj_set_width(ui_ContainerDataRH, 128);
    lv_obj_set_height(ui_ContainerDataRH, 68);
    lv_obj_set_x(ui_ContainerDataRH, 36);
    lv_obj_set_y(ui_ContainerDataRH, 0);
    lv_obj_set_align(ui_ContainerDataRH, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataRH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataRH = lv_obj_create(ui_ContainerDataRH);
    lv_obj_remove_style_all(ui_ContainerLabelDataRH);
    lv_obj_set_height(ui_ContainerLabelDataRH, 28);
    lv_obj_set_width(ui_ContainerLabelDataRH, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataRH, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataRH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValueRH = lv_label_create(ui_ContainerLabelDataRH);
    lv_obj_set_width(ui_LabelValueRH, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValueRH, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValueRH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueRH, "0");
    lv_obj_set_style_text_align(ui_LabelValueRH, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueRH, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitRH = lv_label_create(ui_ContainerLabelDataRH);
    lv_obj_set_width(ui_LabelUnitRH, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitRH, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitRH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitRH, "%");
    lv_obj_set_style_text_align(ui_LabelUnitRH, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitRH, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValueRH = lv_bar_create(ui_ContainerDataRH);
    lv_obj_set_width(ui_BarValueRH, 128);
    lv_obj_set_height(ui_BarValueRH, 4);
    lv_obj_set_x(ui_BarValueRH, 0);
    lv_obj_set_y(ui_BarValueRH, 36);
    lv_obj_set_align(ui_BarValueRH, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValueRH, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValueRH, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNameRH = lv_label_create(ui_ContainerDataRH);
    lv_obj_set_height(ui_LabelNameRH, 20);
    lv_obj_set_width(ui_LabelNameRH, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNameRH, 0);
    lv_obj_set_y(ui_LabelNameRH, 48);
    lv_obj_set_align(ui_LabelNameRH, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNameRH, "RH");
    lv_obj_set_style_text_align(ui_LabelNameRH, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameRH, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLineRH = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerLineRH);
    lv_obj_set_width(ui_ContainerLineRH, 162);
    lv_obj_set_height(ui_ContainerLineRH, 1);
    lv_obj_set_x(ui_ContainerLineRH, 0);
    lv_obj_set_y(ui_ContainerLineRH, 209);
    lv_obj_set_align(ui_ContainerLineRH, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLineRH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLineRH, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLineRH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverTVOC = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerCoverTVOC);
    lv_obj_set_width(ui_ContainerCoverTVOC, 212);
    lv_obj_set_height(ui_ContainerCoverTVOC, 112);
    lv_obj_set_x(ui_ContainerCoverTVOC, 0);
    lv_obj_set_y(ui_ContainerCoverTVOC, 208);
    lv_obj_set_align(ui_ContainerCoverTVOC, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverTVOC, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTVOC = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_set_width(ui_PanelTVOC, 164);
    lv_obj_set_height(ui_PanelTVOC, 92);
    lv_obj_set_x(ui_PanelTVOC, 0);
    lv_obj_set_y(ui_PanelTVOC, 218);
    lv_obj_set_align(ui_PanelTVOC, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTVOC, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTVOC, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTVOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTVOC, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTVOC, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTVOC = lv_obj_create(ui_PanelTVOC);
    lv_obj_remove_style_all(ui_ContainerTVOC);
    lv_obj_set_width(ui_ContainerTVOC, 164);
    lv_obj_set_height(ui_ContainerTVOC, 68);
    lv_obj_set_align(ui_ContainerTVOC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTVOC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconTVOC = lv_img_create(ui_ContainerTVOC);
    lv_img_set_src(ui_ImageIconTVOC, &ui_img_images_tvoc_white_png);
    lv_obj_set_width(ui_ImageIconTVOC, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImageIconTVOC, LV_SIZE_CONTENT);    /// 24
    lv_obj_add_flag(ui_ImageIconTVOC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDataTVOC = lv_obj_create(ui_ContainerTVOC);
    lv_obj_remove_style_all(ui_ContainerDataTVOC);
    lv_obj_set_width(ui_ContainerDataTVOC, 128);
    lv_obj_set_height(ui_ContainerDataTVOC, 68);
    lv_obj_set_x(ui_ContainerDataTVOC, 36);
    lv_obj_set_y(ui_ContainerDataTVOC, 0);
    lv_obj_set_align(ui_ContainerDataTVOC, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerDataTVOC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLabelDataTVOC = lv_obj_create(ui_ContainerDataTVOC);
    lv_obj_remove_style_all(ui_ContainerLabelDataTVOC);
    lv_obj_set_height(ui_ContainerLabelDataTVOC, 28);
    lv_obj_set_width(ui_ContainerLabelDataTVOC, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_align(ui_ContainerLabelDataTVOC, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLabelDataTVOC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelValueTVOC = lv_label_create(ui_ContainerLabelDataTVOC);
    lv_obj_set_width(ui_LabelValueTVOC, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelValueTVOC, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelValueTVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueTVOC, "0");
    lv_obj_set_style_text_align(ui_LabelValueTVOC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueTVOC, &ui_font_Poppins_Light_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnitTVOC = lv_label_create(ui_ContainerLabelDataTVOC);
    lv_obj_set_width(ui_LabelUnitTVOC, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_LabelUnitTVOC, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelUnitTVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUnitTVOC, "ppb");
    lv_obj_set_style_text_align(ui_LabelUnitTVOC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitTVOC, &ui_font_Poppins_Light_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValueTVOC = lv_bar_create(ui_ContainerDataTVOC);
    lv_bar_set_range(ui_BarValueTVOC, 0, 65000);
    lv_obj_set_width(ui_BarValueTVOC, 128);
    lv_obj_set_height(ui_BarValueTVOC, 4);
    lv_obj_set_x(ui_BarValueTVOC, 0);
    lv_obj_set_y(ui_BarValueTVOC, 36);
    lv_obj_set_align(ui_BarValueTVOC, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_BarValueTVOC, lv_color_hex(0x20A979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarValueTVOC, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelNameTVOC = lv_label_create(ui_ContainerDataTVOC);
    lv_obj_set_height(ui_LabelNameTVOC, 20);
    lv_obj_set_width(ui_LabelNameTVOC, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_x(ui_LabelNameTVOC, 0);
    lv_obj_set_y(ui_LabelNameTVOC, 48);
    lv_obj_set_align(ui_LabelNameTVOC, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelNameTVOC, "TVOC");
    lv_obj_set_style_text_align(ui_LabelNameTVOC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameTVOC, &ui_font_OpenSans_Regular_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLineTVOC = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerLineTVOC);
    lv_obj_set_width(ui_ContainerLineTVOC, 162);
    lv_obj_set_height(ui_ContainerLineTVOC, 1);
    lv_obj_set_x(ui_ContainerLineTVOC, 0);
    lv_obj_set_y(ui_ContainerLineTVOC, 318);
    lv_obj_set_align(ui_ContainerLineTVOC, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLineTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLineTVOC, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLineTVOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCoverSetting = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_remove_style_all(ui_ContainerCoverSetting);
    lv_obj_set_width(ui_ContainerCoverSetting, 212);
    lv_obj_set_height(ui_ContainerCoverSetting, 131);
    lv_obj_set_x(ui_ContainerCoverSetting, 0);
    lv_obj_set_y(ui_ContainerCoverSetting, 317);
    lv_obj_set_align(ui_ContainerCoverSetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerCoverSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerCoverSetting, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerCoverSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetting = lv_obj_create(ui_ContainerRegionRight);
    lv_obj_set_width(ui_PanelSetting, 164);
    lv_obj_set_height(ui_PanelSetting, 92);
    lv_obj_set_x(ui_PanelSetting, 0);
    lv_obj_set_y(ui_PanelSetting, 327);
    lv_obj_set_align(ui_PanelSetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetting, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSetting, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSetting, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSetting, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSetting = lv_obj_create(ui_PanelSetting);
    lv_obj_remove_style_all(ui_ContainerSetting);
    lv_obj_set_width(ui_ContainerSetting, 164);
    lv_obj_set_height(ui_ContainerSetting, 68);
    lv_obj_set_align(ui_ContainerSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIconSetting = lv_img_create(ui_ContainerSetting);
    lv_img_set_src(ui_ImageIconSetting, &ui_img_images_setting32_32_png);
    lv_obj_set_width(ui_ImageIconSetting, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageIconSetting, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_align(ui_ImageIconSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIconSetting, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ContainerCoverPM1, ui_event_ContainerCoverPM1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelPM1, ui_event_PanelPM1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLinePM1, ui_event_ContainerLinePM1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverPM25, ui_event_ContainerCoverPM25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelPM25, ui_event_PanelPM25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLinePM25, ui_event_ContainerLinePM25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverPM10, ui_event_ContainerCoverPM10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelPM10, ui_event_PanelPM10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLinePM10, ui_event_ContainerLinePM10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverCO2, ui_event_ContainerCoverCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelCO2, ui_event_PanelCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverTEMP, ui_event_ContainerCoverTEMP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelTEMP, ui_event_PanelTEMP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLineTEMP, ui_event_ContainerLineTEMP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverRH, ui_event_ContainerCoverRH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelRH, ui_event_PanelRH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLineRH, ui_event_ContainerLineRH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverTVOC, ui_event_ContainerCoverTVOC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelTVOC, ui_event_PanelTVOC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerLineTVOC, ui_event_ContainerLineTVOC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerCoverSetting, ui_event_ContainerCoverSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelSetting, ui_event_PanelSetting, LV_EVENT_ALL, NULL);

    aqi_indicator_ui_init();
    aqi_sensor_init();
}
