// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "../ui.h"

void ui_ScreenLoadAQI_screen_init(void)
{
    ui_ScreenLoadAQI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoadAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenLoadAQI, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenLoadAQI, lv_color_hex(0x18191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLoadAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoad = lv_obj_create(ui_ScreenLoadAQI);
    lv_obj_remove_style_all(ui_ContainerLoad);
    lv_obj_set_width(ui_ContainerLoad, 800);
    lv_obj_set_height(ui_ContainerLoad, 480);
    lv_obj_set_align(ui_ContainerLoad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLoad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadStatus = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerLoadStatus);
    lv_obj_set_width(ui_ContainerLoadStatus, 800);
    lv_obj_set_height(ui_ContainerLoadStatus, 47);
    lv_obj_set_align(ui_ContainerLoadStatus, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLoadStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContaierLoadLeftSide = lv_obj_create(ui_ContainerLoadStatus);
    lv_obj_remove_style_all(ui_ContaierLoadLeftSide);
    lv_obj_set_width(ui_ContaierLoadLeftSide, 54);
    lv_obj_set_height(ui_ContaierLoadLeftSide, 21);
    lv_obj_set_x(ui_ContaierLoadLeftSide, 32);
    lv_obj_set_y(ui_ContaierLoadLeftSide, 14);
    lv_obj_clear_flag(ui_ContaierLoadLeftSide, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelLoadTime = lv_label_create(ui_ContaierLoadLeftSide);
    lv_obj_set_width(ui_LabelLoadTime, 54);
    lv_obj_set_height(ui_LabelLoadTime, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelLoadTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoadTime, "9:41");
    lv_obj_set_style_text_align(ui_LabelLoadTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoadTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoadRightSide = lv_obj_create(ui_ContainerLoadStatus);
    lv_obj_remove_style_all(ui_ContainerLoadRightSide);
    lv_obj_set_width(ui_ContainerLoadRightSide, 79);
    lv_obj_set_height(ui_ContainerLoadRightSide, 13);
    lv_obj_set_x(ui_ContainerLoadRightSide, -32);
    lv_obj_set_y(ui_ContainerLoadRightSide, 19);
    lv_obj_set_align(ui_ContainerLoadRightSide, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ContainerLoadRightSide, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadMobileSignal = lv_obj_create(ui_ContainerLoadRightSide);
    lv_obj_remove_style_all(ui_ContainerLoadMobileSignal);
    lv_obj_set_width(ui_ContainerLoadMobileSignal, 18);
    lv_obj_set_height(ui_ContainerLoadMobileSignal, 12);
    lv_obj_set_align(ui_ContainerLoadMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerLoadMobileSignal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLoadMobileSignal = lv_img_create(ui_ContainerLoadMobileSignal);
    lv_img_set_src(ui_ImageLoadMobileSignal, &ui_img_images_mobilesignal4_png);
    lv_obj_set_width(ui_ImageLoadMobileSignal, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageLoadMobileSignal, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_ImageLoadMobileSignal, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageLoadMobileSignal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadMobileSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadWifi = lv_obj_create(ui_ContainerLoadRightSide);
    lv_obj_remove_style_all(ui_ContainerLoadWifi);
    lv_obj_set_width(ui_ContainerLoadWifi, 17);
    lv_obj_set_height(ui_ContainerLoadWifi, 12);
    lv_obj_set_x(ui_ContainerLoadWifi, 26);
    lv_obj_set_y(ui_ContainerLoadWifi, 0);
    lv_obj_set_align(ui_ContainerLoadWifi, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerLoadWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLoadWifi = lv_img_create(ui_ContainerLoadWifi);
    lv_img_set_src(ui_ImageLoadWifi, &ui_img_images_wifi3_png);
    lv_obj_set_width(ui_ImageLoadWifi, LV_SIZE_CONTENT);   /// 6
    lv_obj_set_height(ui_ImageLoadWifi, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_align(ui_ImageLoadWifi, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageLoadWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadBattery = lv_obj_create(ui_ContainerLoadRightSide);
    lv_obj_remove_style_all(ui_ContainerLoadBattery);
    lv_obj_set_width(ui_ContainerLoadBattery, 28);
    lv_obj_set_height(ui_ContainerLoadBattery, 13);
    lv_obj_set_x(ui_ContainerLoadBattery, 51);
    lv_obj_set_y(ui_ContainerLoadBattery, 0);
    lv_obj_set_align(ui_ContainerLoadBattery, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerLoadBattery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLoadBattery = lv_img_create(ui_ContainerLoadBattery);
    lv_img_set_src(ui_ImageLoadBattery, &ui_img_images_batteryoutline_png);
    lv_obj_set_width(ui_ImageLoadBattery, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_ImageLoadBattery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(ui_ImageLoadBattery, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageLoadBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarLoadBattery = lv_bar_create(ui_ContainerLoadBattery);
    lv_bar_set_value(ui_BarLoadBattery, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarLoadBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarLoadBattery, 21);
    lv_obj_set_height(ui_BarLoadBattery, 9);
    lv_obj_set_x(ui_BarLoadBattery, 2);
    lv_obj_set_y(ui_BarLoadBattery, 0);
    lv_obj_set_align(ui_BarLoadBattery, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_BarLoadBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarLoadBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarLoadBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarLoadBattery, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarLoadBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarLoadBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerLoadMain = lv_obj_create(ui_ContainerLoad);
    lv_obj_remove_style_all(ui_ContainerLoadMain);
    lv_obj_set_width(ui_ContainerLoadMain, 800);
    lv_obj_set_height(ui_ContainerLoadMain, 427);
    lv_obj_set_x(ui_ContainerLoadMain, 0);
    lv_obj_set_y(ui_ContainerLoadMain, 53);
    lv_obj_set_align(ui_ContainerLoadMain, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerLoadMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerLoadMain, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerLoadMain, lv_color_hex(0x201F26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLoadMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoadProgress = lv_spinner_create(ui_ContainerLoadMain, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoadProgress, 348);
    lv_obj_set_height(ui_SpinnerLoadProgress, 348);
    lv_obj_set_x(ui_SpinnerLoadProgress, 226);
    lv_obj_set_y(ui_SpinnerLoadProgress, 21);
    lv_obj_clear_flag(ui_SpinnerLoadProgress, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerLoadProgress, lv_color_hex(0x30323B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerLoadProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerLoadProgress, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_SpinnerLoadProgress, &ui_img_images_line_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerLoading = lv_obj_create(ui_SpinnerLoadProgress);
    lv_obj_remove_style_all(ui_ContainerLoading);
    lv_obj_set_width(ui_ContainerLoading, 268);
    lv_obj_set_height(ui_ContainerLoading, 92);
    lv_obj_set_x(ui_ContainerLoading, 40);
    lv_obj_set_y(ui_ContainerLoading, 154);
    lv_obj_clear_flag(ui_ContainerLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoadName = lv_obj_create(ui_ContainerLoading);
    lv_obj_remove_style_all(ui_ContainerLoadName);
    lv_obj_set_width(ui_ContainerLoadName, 268);
    lv_obj_set_height(ui_ContainerLoadName, 38);
    lv_obj_clear_flag(ui_ContainerLoadName, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLoadName = lv_img_create(ui_ContainerLoadName);
    lv_img_set_src(ui_ImageLoadName, &ui_img_images_load_png);
    lv_obj_set_width(ui_ImageLoadName, LV_SIZE_CONTENT);   /// 268
    lv_obj_set_height(ui_ImageLoadName, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_align(ui_ImageLoadName, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLoadName, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoadName, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelLoading = lv_label_create(ui_SpinnerLoadProgress);
    lv_obj_set_width(ui_LabelLoading, 90);
    lv_obj_set_height(ui_LabelLoading, 21);
    lv_obj_set_x(ui_LabelLoading, 0);
    lv_obj_set_y(ui_LabelLoading, 62);
    lv_obj_set_align(ui_LabelLoading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoading, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoading, lv_color_hex(0x6C748B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLoading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoading, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenLoadAQI, ui_event_ScreenLoadAQI, LV_EVENT_ALL, NULL);

}
