
#ifndef _AQI_CONFIG_DEFINE_H
#define _AQI_CONFIG_DEFINE_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * SPIFFS configuration
 */
#define AQI_CONFIG_SPIFFS_BASE_PATH "/spiffs"
#define AQI_CONFIG_SPIFFS_FILE_PATH "/spiffs/config.json"
#define AQI_CONFIG_SPIFFS_MAX_FILES 1
#define AQI_CONFIG_SPIFFS_MAX_SIZE  1500

/*
 * JSON keys for the theme configuration
 */
#define AQI_CONFIG_THEME_KEY "theme"
#define AQI_CONFIG_THEME_KEY_COLOR_PRIMARY   "color_primary"
#define AQI_CONFIG_THEME_KEY_COLOR_SECONDARY "color_secondary"
#define AQI_CONFIG_THEME_KEY_DARK_MODE       "dark_mode"

/*
 * JSON keys for the sensor configuration
 */
#define AQI_CONFIG_SENSOR_KEY "sensor"
#define AQI_CONFIG_SENSOR_KEY_PERIOD_MS     "period_ms"
#define AQI_CONFIG_SENSOR_KEY_ERROR_MESSAGE "error_message"

/*
 * JSON keys for the indicators configuration
 */
#define AQI_CONFIG_INDICATOR_KEY "indicator"
#define AQI_CONFIG_INDICATOR_KEY_THRESHOLD_WARNING "threshold_warning"
#define AQI_CONFIG_INDICATOR_KEY_THRESHOLD_BAD     "threshold_bad"
#define AQI_CONFIG_INDICATOR_KEY_COLOR_GOOD        "color_good"
#define AQI_CONFIG_INDICATOR_KEY_COLOR_WARNING     "color_warning"
#define AQI_CONFIG_INDICATOR_KEY_COLOR_BAD         "color_bad"
#define AQI_CONFIG_INDICATOR_KEY_NAME              "name"
#define AQI_CONFIG_INDICATOR_KEY_UNIT              "unit"

/*
 * Default values for the theme
 */
#define AQI_CONFIG_THEME_COLOR_PRIMARY_DEFAULT   LV_PALETTE_BLUE
#define AQI_CONFIG_THEME_COLOR_SECONDARY_DEFAULT LV_PALETTE_RED
#define AQI_CONFIG_THEME_DARK_MODE_DEFAULT       true

/*
 * Default values for the sensor
 */
#define AQI_CONFIG_SENSOR_PERIOD_MS_DEFAULT     1000
#define AQI_CONFIG_SENSOR_ERROR_MESSAGE_DEFAULT "Sensor measurement error"

/*
 * Default values for the indicators
 */
#define BAR_COLOR_GOOD    0x20A979
#define BAR_COLOR_WARNING 0xF79009
#define BAR_COLOR_BAD     0xFF2D46

#define AQI_CONFIG_INDICATOR_PM1_THRESHOLD_WARNING_DEFAULT  300
#define AQI_CONFIG_INDICATOR_PM1_THRESHOLD_BAD_DEFAULT      400
#define AQI_CONFIG_INDICATOR_PM1_COLOR_GOOD_DEFAULT         BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_PM1_COLOR_WARNING_DEFAULT      BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_PM1_COLOR_BAD_DEFAULT          BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_PM1_NAME_DEFAULT               "PM₁"
#define AQI_CONFIG_INDICATOR_PM1_UNIT_DEFAULT               "µg/m³"

#define AQI_CONFIG_INDICATOR_PM25_THRESHOLD_WARNING_DEFAULT 500
#define AQI_CONFIG_INDICATOR_PM25_THRESHOLD_BAD_DEFAULT     800
#define AQI_CONFIG_INDICATOR_PM25_COLOR_GOOD_DEFAULT        BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_PM25_COLOR_WARNING_DEFAULT     BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_PM25_COLOR_BAD_DEFAULT         BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_PM25_NAME_DEFAULT              "PM₂.₅"
#define AQI_CONFIG_INDICATOR_PM25_UNIT_DEFAULT              "µg/m³"

#define AQI_CONFIG_INDICATOR_PM10_THRESHOLD_WARNING_DEFAULT 800
#define AQI_CONFIG_INDICATOR_PM10_THRESHOLD_BAD_DEFAULT     1300
#define AQI_CONFIG_INDICATOR_PM10_COLOR_GOOD_DEFAULT        BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_PM10_COLOR_WARNING_DEFAULT     BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_PM10_COLOR_BAD_DEFAULT         BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_PM10_NAME_DEFAULT              "PM₁₀"
#define AQI_CONFIG_INDICATOR_PM10_UNIT_DEFAULT              "µg/m³"

#define AQI_CONFIG_INDICATOR_CO2_THRESHOLD_WARNING_DEFAULT  30000
#define AQI_CONFIG_INDICATOR_CO2_THRESHOLD_BAD_DEFAULT      50000
#define AQI_CONFIG_INDICATOR_CO2_COLOR_GOOD_DEFAULT         BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_CO2_COLOR_WARNING_DEFAULT      BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_CO2_COLOR_BAD_DEFAULT          BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_CO2_NAME_DEFAULT               "CO₂"
#define AQI_CONFIG_INDICATOR_CO2_UNIT_DEFAULT               "ppm"

#define AQI_CONFIG_INDICATOR_TEMP_THRESHOLD_WARNING_DEFAULT 25
#define AQI_CONFIG_INDICATOR_TEMP_THRESHOLD_BAD_DEFAULT     40
#define AQI_CONFIG_INDICATOR_TEMP_COLOR_GOOD_DEFAULT        BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_TEMP_COLOR_WARNING_DEFAULT     BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_TEMP_COLOR_BAD_DEFAULT         BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_TEMP_NAME_DEFAULT              "TEMP"
#define AQI_CONFIG_INDICATOR_TEMP_UNIT_DEFAULT              "°C"

#define AQI_CONFIG_INDICATOR_RH_THRESHOLD_WARNING_DEFAULT   50
#define AQI_CONFIG_INDICATOR_RH_THRESHOLD_BAD_DEFAULT       80
#define AQI_CONFIG_INDICATOR_RH_COLOR_GOOD_DEFAULT          BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_RH_COLOR_WARNING_DEFAULT       BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_RH_COLOR_BAD_DEFAULT           BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_RH_NAME_DEFAULT                "RH"
#define AQI_CONFIG_INDICATOR_RH_UNIT_DEFAULT                "%"

#define AQI_CONFIG_INDICATOR_TVOC_THRESHOLD_WARNING_DEFAULT 30000
#define AQI_CONFIG_INDICATOR_TVOC_THRESHOLD_BAD_DEFAULT     50000
#define AQI_CONFIG_INDICATOR_TVOC_COLOR_GOOD_DEFAULT        BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_TVOC_COLOR_WARNING_DEFAULT     BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_TVOC_COLOR_BAD_DEFAULT         BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_TVOC_NAME_DEFAULT              "TVOC"
#define AQI_CONFIG_INDICATOR_TVOC_UNIT_DEFAULT              "ppb"

#define AQI_CONFIG_INDICATOR_AQI_THRESHOLD_WARNING_DEFAULT  3
#define AQI_CONFIG_INDICATOR_AQI_THRESHOLD_BAD_DEFAULT      5
#define AQI_CONFIG_INDICATOR_AQI_COLOR_GOOD_DEFAULT         BAR_COLOR_GOOD
#define AQI_CONFIG_INDICATOR_AQI_COLOR_WARNING_DEFAULT      BAR_COLOR_WARNING
#define AQI_CONFIG_INDICATOR_AQI_COLOR_BAD_DEFAULT          BAR_COLOR_BAD
#define AQI_CONFIG_INDICATOR_AQI_NAME_DEFAULT               ""
#define AQI_CONFIG_INDICATOR_AQI_UNIT_DEFAULT               "AQI"

/*
 * Default values for the indicator configuration
 */
#define AQI_CONFIG_INDICATOR_DEFAULT(INDEX)\
{\
    .threshold_warning = AQI_CONFIG_INDICATOR_##INDEX##_THRESHOLD_WARNING_DEFAULT,\
    .threshold_bad = AQI_CONFIG_INDICATOR_##INDEX##_THRESHOLD_BAD_DEFAULT,\
    .color_good = AQI_CONFIG_INDICATOR_##INDEX##_COLOR_GOOD_DEFAULT,\
    .color_warning = AQI_CONFIG_INDICATOR_##INDEX##_COLOR_WARNING_DEFAULT,\
    .color_bad = AQI_CONFIG_INDICATOR_##INDEX##_COLOR_BAD_DEFAULT,\
    .name = AQI_CONFIG_INDICATOR_##INDEX##_NAME_DEFAULT,\
    .unit = AQI_CONFIG_INDICATOR_##INDEX##_UNIT_DEFAULT\
}

/*
 * Default values for the entire configuration
 */
#define AQI_CONFIG_DEFAULT()\
{\
    .theme = {\
        .color_primary = AQI_CONFIG_THEME_COLOR_PRIMARY_DEFAULT,\
        .color_secondary = AQI_CONFIG_THEME_COLOR_SECONDARY_DEFAULT,\
        .dark_mode = AQI_CONFIG_THEME_DARK_MODE_DEFAULT\
    },\
    .sensor = {\
        .period_ms = AQI_CONFIG_SENSOR_PERIOD_MS_DEFAULT,\
        .error_message = AQI_CONFIG_SENSOR_ERROR_MESSAGE_DEFAULT\
    },\
    .indicator = {\
        AQI_CONFIG_INDICATOR_DEFAULT(PM1),\
        AQI_CONFIG_INDICATOR_DEFAULT(PM25),\
        AQI_CONFIG_INDICATOR_DEFAULT(PM10),\
        AQI_CONFIG_INDICATOR_DEFAULT(CO2),\
        AQI_CONFIG_INDICATOR_DEFAULT(TEMP),\
        AQI_CONFIG_INDICATOR_DEFAULT(RH),\
        AQI_CONFIG_INDICATOR_DEFAULT(TVOC),\
        AQI_CONFIG_INDICATOR_DEFAULT(AQI)\
    }\
}

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
