// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLoadAQI
void ui_ScreenLoadAQI_screen_init(void);
void ui_event_ScreenLoadAQI(lv_event_t * e);
lv_obj_t * ui_ScreenLoadAQI;
lv_obj_t * ui_ContainerLoad;
lv_obj_t * ui_ContainerStatus;
lv_obj_t * ui_ContaierStatusLeft;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_ContainerStatusRight;
lv_obj_t * ui_ContainerMobileSignal;
lv_obj_t * ui_ImageMobileSignal;
lv_obj_t * ui_ContainerWifiSignal;
lv_obj_t * ui_ImageWifiSignal;
lv_obj_t * ui_ContainerBattery;
lv_obj_t * ui_ImageBattery;
lv_obj_t * ui_BarBattery;
lv_obj_t * ui_ContainerLoadMain;
lv_obj_t * ui_SpinnerLoadProgress;
lv_obj_t * ui_ContainerLoading;
lv_obj_t * ui_ContainerLoadName;
lv_obj_t * ui_ImageLoadName;
lv_obj_t * ui_LabelLoading;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSettingAQI
void ui_ScreenSettingAQI_screen_init(void);
lv_obj_t * ui_ScreenSettingAQI;
lv_obj_t * ui_ContainerSetting;
lv_obj_t * ui_ContainerSettingMain;
lv_obj_t * ui_ContainerSettingLanguage;
lv_obj_t * ui_ContainerSettingLanguageTitle;
lv_obj_t * ui_ImageSettingLanguageTitleIcon;
lv_obj_t * ui_LabelSettingLanguageTitleName;
lv_obj_t * ui_ContainerSettingCountry;
lv_obj_t * ui_ContainerSettingCountryTitle;
lv_obj_t * ui_ImageSettingCountryTitleIcon;
lv_obj_t * ui_LabelSettingCountryTitleName;
lv_obj_t * ui_ContainerSettingWifi;
lv_obj_t * ui_ContainerSettingWifiTitle;
lv_obj_t * ui_ImageSettingWifiTitleIcon;
lv_obj_t * ui_LabelSettingWifiTitleName;
lv_obj_t * ui_ContainerSettingWifiEnable;
lv_obj_t * ui_ContainerSettingWifiEnableIcon;
lv_obj_t * ui_ImageSettingWifiEnableIcon;
lv_obj_t * ui_LabelSettingWifiEnable;
lv_obj_t * ui_SwitchSettingWifiEnable;
lv_obj_t * ui_ContainerSettingButton;
lv_obj_t * ui_ButtonSettingBack;
lv_obj_t * ui_LabelSettingBackButton;
lv_obj_t * ui_ButtonSettingNext;
lv_obj_t * ui_LabelSettingNextButton;
lv_obj_t * ui_ContainerSettingStage;
lv_obj_t * ui_ImageSettingStageLanguage;
lv_obj_t * ui_ImageSettingStageCountry;
lv_obj_t * ui_ImageSettingStageWifi;
lv_obj_t * ui_ContainerWifiPassword;
lv_obj_t * ui_ContainerWifiSelect;
lv_obj_t * ui_ContainerWifiSelectIcon;
lv_obj_t * ui_ImageWifiSelectIcon;
lv_obj_t * ui_LabelWifiSelectName;
lv_obj_t * ui_ImageWifiSelectExit;
lv_obj_t * ui_ContainerWifiPasswordType;
lv_obj_t * ui_ImageWifiPasswordLock;
lv_obj_t * ui_TextWifiPasswordType;
lv_obj_t * ui_LabelWifiPasswordShow;
lv_obj_t * ui_ButtonWifiConnect;
lv_obj_t * ui_LabelWifiConnectButton;
lv_obj_t * ui_KeyboardWifiPassword;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenIndicatorAQI
void ui_ScreenIndicatorAQI_screen_init(void);
lv_obj_t * ui_ScreenIndicatorAQI;
lv_obj_t * ui_ContainerRegionLeft;
lv_obj_t * ui_ContainerCoverPM1;
lv_obj_t * ui_PanelPM1;
lv_obj_t * ui_ContainerPM1;
lv_obj_t * ui_ImageIconPM1;
lv_obj_t * ui_ContainerDataPM1;
lv_obj_t * ui_ContainerLabelDataPM1;
lv_obj_t * ui_LabelValuePM1;
lv_obj_t * ui_LabelUnitPM1;
lv_obj_t * ui_BarValuePM1;
lv_obj_t * ui_LabelNamePM1;
lv_obj_t * ui_ContainerLinePM1;
lv_obj_t * ui_ContainerCoverPM25;
lv_obj_t * ui_PanelPM25;
lv_obj_t * ui_ContainerPM25;
lv_obj_t * ui_ImageIconPM25;
lv_obj_t * ui_ContainerDataPM25;
lv_obj_t * ui_ContainerLabelDataPM25;
lv_obj_t * ui_LabelValuePM25;
lv_obj_t * ui_LabelUnitPM25;
lv_obj_t * ui_BarValuePM25;
lv_obj_t * ui_LabelNamePM25;
lv_obj_t * ui_ContainerLinePM25;
lv_obj_t * ui_ContainerCoverPM10;
lv_obj_t * ui_PanelPM10;
lv_obj_t * ui_ContainerPM10;
lv_obj_t * ui_ImageIconPM10;
lv_obj_t * ui_ContainerDataPM10;
lv_obj_t * ui_ContainerLabelDataPM10;
lv_obj_t * ui_LabelValuePM10;
lv_obj_t * ui_LabelUnitPM10;
lv_obj_t * ui_BarValuePM10;
lv_obj_t * ui_LabelNamePM10;
lv_obj_t * ui_ContainerLinePM10;
lv_obj_t * ui_ContainerCoverCO2;
lv_obj_t * ui_PanelCO2;
lv_obj_t * ui_ContainerCO2;
lv_obj_t * ui_ImageIconCO2;
lv_obj_t * ui_ContainerDataCO2;
lv_obj_t * ui_ContainerLabelDataCO2;
lv_obj_t * ui_LabelValueCO2;
lv_obj_t * ui_LabelUnitCO2;
lv_obj_t * ui_BarValueCO2;
lv_obj_t * ui_LabelNameCO2;
lv_obj_t * ui_PanelLineCenterLeft;
lv_obj_t * ui_ContainerIndicator;
lv_obj_t * ui_ContainerMain;
lv_obj_t * ui_ContainerSelectAQI;
lv_obj_t * ui_LabelValueSelectAQI;
lv_obj_t * ui_ContaierInforSelectAQI;
lv_obj_t * ui_ContainerLevelSelectAQI;
lv_obj_t * ui_ContainerAlignLevelSelectAQI;
lv_obj_t * ui_ImageLevelSelectAQI;
lv_obj_t * ui_LabelUnitSelectAQI;
lv_obj_t * ui_ContainerNameSelectAQI;
lv_obj_t * ui_LabelNameSelectAQI;
lv_obj_t * ui_PanelLineCenterRight;
lv_obj_t * ui_ContainerRegionRight;
lv_obj_t * ui_ContainerCoverTEMP;
lv_obj_t * ui_PanelTEMP;
lv_obj_t * ui_ContainerTEMP;
lv_obj_t * ui_ImageIconTEMP;
lv_obj_t * ui_ContainerDataTEMP;
lv_obj_t * ui_ContainerLabelDataTEMP;
lv_obj_t * ui_LabelValueTEMP;
lv_obj_t * ui_LabelUnitTEMP;
lv_obj_t * ui_BarValueTEMP;
lv_obj_t * ui_LabelNameTEMP;
lv_obj_t * ui_ContainerLineTEMP;
lv_obj_t * ui_ContainerCoverRH;
lv_obj_t * ui_PanelRH;
lv_obj_t * ui_ContainerRH;
lv_obj_t * ui_ImageIconRH;
lv_obj_t * ui_ContainerDataRH;
lv_obj_t * ui_ContainerLabelDataRH;
lv_obj_t * ui_LabelValueRH;
lv_obj_t * ui_LabelUnitRH;
lv_obj_t * ui_BarValueRH;
lv_obj_t * ui_LabelNameRH;
lv_obj_t * ui_ContainerLineRH;
lv_obj_t * ui_ContainerCoverTVOC;
lv_obj_t * ui_PanelTVOC;
lv_obj_t * ui_ContainerTVOC;
lv_obj_t * ui_ImageIconTVOC;
lv_obj_t * ui_ContainerDataTVOC;
lv_obj_t * ui_ContainerLabelDataTVOC;
lv_obj_t * ui_LabelValueTVOC;
lv_obj_t * ui_LabelUnitTVOC;
lv_obj_t * ui_BarValueTVOC;
lv_obj_t * ui_LabelNameTVOC;
lv_obj_t * ui_ContainerLineTVOC;
void ui_event_ContainerCoverSetting(lv_event_t * e);
lv_obj_t * ui_ContainerCoverSetting;
void ui_event_PanelSetting(lv_event_t * e);
lv_obj_t * ui_PanelSetting;
lv_obj_t * ui_ContainerSettingIcon;
lv_obj_t * ui_ImageSettingIcon;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_co[1] = {&ui_img_images_co2_png};
const lv_img_dsc_t * ui_imgset_wifi_[1] = {&ui_img_images_wifi_44_png};
const lv_img_dsc_t * ui_imgset_wifi_blue_[1] = {&ui_img_images_wifi_blue_24_png};
const lv_img_dsc_t * ui_imgset_wifi_white_[1] = {&ui_img_images_wifi_white_24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenLoadAQI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenSettingAQI, LV_SCR_LOAD_ANIM_FADE_ON, 700, 300, &ui_ScreenSettingAQI_screen_init);
    }
}

void ui_event_ContainerCoverSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aqi_indicator_setting_click_event(e);
    }
}

void ui_event_PanelSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aqi_indicator_setting_click_event(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    aqi_config_theme_t * theme_config = aqi_config_theme_get();
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(theme_config->color_primary),
                                                      lv_palette_main(theme_config->color_secondary),
                                                      theme_config->dark_mode, LV_FONT_DEFAULT);

    lv_disp_set_theme(dispp, theme);
    ui_ScreenLoadAQI_screen_init();
    ui_ScreenSettingAQI_screen_init();
    ui_ScreenIndicatorAQI_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLoadAQI);

    aqi_indicator_ui_init();
    aqi_setting_init();
    aqi_utility_init();
    aqi_sensor_init();
}
