// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLoadAQI
void ui_ScreenLoadAQI_screen_init(void);
void ui_event_ScreenLoadAQI(lv_event_t * e);
lv_obj_t * ui_ScreenLoadAQI;
lv_obj_t * ui_ContainerLoad;
lv_obj_t * ui_ContainerStatus;
lv_obj_t * ui_ContaierStatusLeft;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_ContainerStatusCenter;
lv_obj_t * ui_ImageSetting;
lv_obj_t * ui_LabelSetting;
lv_obj_t * ui_ContainerStatusRight;
lv_obj_t * ui_ContainerMobileSignal;
lv_obj_t * ui_ImageMobileSignal;
lv_obj_t * ui_ContainerWifiSignal;
lv_obj_t * ui_ImageWifiSignal;
lv_obj_t * ui_ContainerBattery;
lv_obj_t * ui_ImageBattery;
lv_obj_t * ui_BarBattery;
lv_obj_t * ui_ContainerLoadMain;
lv_obj_t * ui_ImageLoadLogo;
lv_obj_t * ui_BarLoading;
lv_obj_t * ui_LabelLoading;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSettingAQI
void ui_ScreenSettingAQI_screen_init(void);
lv_obj_t * ui_ScreenSettingAQI;
lv_obj_t * ui_ContainerSetting;
lv_obj_t * ui_ContainerSettingMain;
lv_obj_t * ui_ContainerSettingTab;
lv_obj_t * ui_ContainerSettingTabHeader;
lv_obj_t * ui_ImageSettingTabSwitchBack;
lv_obj_t * ui_LabelSettingTabTitleName;
lv_obj_t * ui_SwitchSettingTabDarkMode;
lv_obj_t * ui_ContainerSettingTabBody;
lv_obj_t * ui_ContainerSettingTabBody1;
lv_obj_t * ui_ContainerSettingTabSound;
lv_obj_t * ui_ContainerSettingTabSoundIcon;
lv_obj_t * ui_ImageSettingTabSoundIcon;
lv_obj_t * ui_LabelSettingTabSoundName;
lv_obj_t * ui_SwitchSettingTabSoundEnable;
lv_obj_t * ui_ContainerSettingTabWifi;
lv_obj_t * ui_ContainerSettingTabWifiIcon;
lv_obj_t * ui_ImageSettingTabWifiIcon;
lv_obj_t * ui_LabelSettingTabWifiName;
lv_obj_t * ui_SwitchSettingTabWifiEnable;
lv_obj_t * ui_ContainerSettingTabHistory;
lv_obj_t * ui_ContainerSettingTabHistoryIcon;
lv_obj_t * ui_ImageSettingTabHistoryIcon;
lv_obj_t * ui_LabelSettingTabHistoryName;
lv_obj_t * ui_SwitchSettingTabHistoryEnable;
lv_obj_t * ui_ContainerSettingTabBody2;
lv_obj_t * ui_ContainerSettingTabLanguage;
lv_obj_t * ui_ImageSettingTabLanguageIcon;
lv_obj_t * ui_LabelSettingTabLanguageName;
lv_obj_t * ui_ImageSettingTabLanguageChange;
lv_obj_t * ui_ContainerSettingTabCountry;
lv_obj_t * ui_ImageSettingTabCountryIcon;
lv_obj_t * ui_LabelSettingTabCountryName;
lv_obj_t * ui_ImageSettingTabCountryChange;
lv_obj_t * ui_ContainerSettingTabBody3;
lv_obj_t * ui_ContainerSettingTabBluetooth;
lv_obj_t * ui_ContainerSettingTabBluetoothIcon;
lv_obj_t * ui_ImageSettingTabBluetoothIcon;
lv_obj_t * ui_LabelSettingTabBluetoothName;
lv_obj_t * ui_SwitchSettingTabBluetoothEnable;
lv_obj_t * ui_ContainerSettingTabEmailAlert;
lv_obj_t * ui_ContainerSettingTabEmailAlertIcon;
lv_obj_t * ui_ImageSettingTabEmailAlertIcon;
lv_obj_t * ui_LabelSettingTabEmailAlertName;
lv_obj_t * ui_SwitchSettingTabEmailAlertEnable;
lv_obj_t * ui_ContainerSettingTabBody4;
lv_obj_t * ui_ContainerSettingTabWeb;
lv_obj_t * ui_ContainerSettingTabWebIcon;
lv_obj_t * ui_ImageSettingTabWebIcon;
lv_obj_t * ui_LabelSettingTabWebName;
lv_obj_t * ui_ImageSettingTabWebEdit;
lv_obj_t * ui_ContainerSettingTabEmail;
lv_obj_t * ui_ContainerSettingTabEmailIcon;
lv_obj_t * ui_ImageSettingTabEmailIcon;
lv_obj_t * ui_LabelSettingTabEmailName;
lv_obj_t * ui_ImageSettingTabEmailEdit;
lv_obj_t * ui_ContainerSettingLanguage;
lv_obj_t * ui_ContainerSettingLanguageTitle;
lv_obj_t * ui_ImageSettingLanguageTitleIcon;
lv_obj_t * ui_LabelSettingLanguageTitleName;
lv_obj_t * ui_ContainerSettingCountry;
lv_obj_t * ui_ContainerSettingCountryTitle;
lv_obj_t * ui_ImageSettingCountryTitleIcon;
lv_obj_t * ui_LabelSettingCountryTitleName;
lv_obj_t * ui_ContainerSettingWifi;
lv_obj_t * ui_ContainerSettingWifiTitle;
lv_obj_t * ui_ImageSettingWifiTitleIcon;
lv_obj_t * ui_LabelSettingWifiTitleName;
lv_obj_t * ui_ContainerSettingWifiEnable;
lv_obj_t * ui_ContainerSettingWifiEnableIcon;
lv_obj_t * ui_ImageSettingWifiEnableIcon;
lv_obj_t * ui_LabelSettingWifiEnable;
lv_obj_t * ui_SwitchSettingWifiEnable;
lv_obj_t * ui_ContainerSettingButton;
lv_obj_t * ui_ButtonSettingBack;
lv_obj_t * ui_LabelSettingBackButton;
lv_obj_t * ui_ButtonSettingNext;
lv_obj_t * ui_LabelSettingNextButton;
lv_obj_t * ui_ContainerSettingStage;
lv_obj_t * ui_ImageSettingStageLanguage;
lv_obj_t * ui_ImageSettingStageCountry;
lv_obj_t * ui_ImageSettingStageWifi;
lv_obj_t * ui_ButtonSettingSelect;
lv_obj_t * ui_LabelSettingSelectButton;
lv_obj_t * ui_ContainerWifiPassword;
lv_obj_t * ui_ContainerWifiSelect;
lv_obj_t * ui_ContainerWifiSelectIcon;
lv_obj_t * ui_ImageWifiSelectIcon;
lv_obj_t * ui_LabelWifiSelectName;
lv_obj_t * ui_ImageWifiSelectExit;
lv_obj_t * ui_ContainerWifiPasswordType;
lv_obj_t * ui_ImageWifiPasswordLock;
lv_obj_t * ui_TextWifiPasswordType;
lv_obj_t * ui_LabelWifiPasswordShow;
lv_obj_t * ui_ButtonWifiConnect;
lv_obj_t * ui_LabelWifiConnectButton;
lv_obj_t * ui_KeyboardWifiPassword;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenIndicatorAQI
void ui_ScreenIndicatorAQI_screen_init(void);
lv_obj_t * ui_ScreenIndicatorAQI;
lv_obj_t * ui_ContainerRegionLeft;
lv_obj_t * ui_ContainerCoverPM1;
lv_obj_t * ui_PanelPM1;
lv_obj_t * ui_ContainerPM1;
lv_obj_t * ui_ImageIconPM1;
lv_obj_t * ui_ContainerDataPM1;
lv_obj_t * ui_ContainerLabelDataPM1;
lv_obj_t * ui_LabelValuePM1;
lv_obj_t * ui_LabelUnitPM1;
lv_obj_t * ui_BarValuePM1;
lv_obj_t * ui_LabelNamePM1;
lv_obj_t * ui_ContainerLinePM1;
lv_obj_t * ui_ContainerCoverPM25;
lv_obj_t * ui_PanelPM25;
lv_obj_t * ui_ContainerPM25;
lv_obj_t * ui_ImageIconPM25;
lv_obj_t * ui_ContainerDataPM25;
lv_obj_t * ui_ContainerLabelDataPM25;
lv_obj_t * ui_LabelValuePM25;
lv_obj_t * ui_LabelUnitPM25;
lv_obj_t * ui_BarValuePM25;
lv_obj_t * ui_LabelNamePM25;
lv_obj_t * ui_ContainerLinePM25;
lv_obj_t * ui_ContainerCoverPM10;
lv_obj_t * ui_PanelPM10;
lv_obj_t * ui_ContainerPM10;
lv_obj_t * ui_ImageIconPM10;
lv_obj_t * ui_ContainerDataPM10;
lv_obj_t * ui_ContainerLabelDataPM10;
lv_obj_t * ui_LabelValuePM10;
lv_obj_t * ui_LabelUnitPM10;
lv_obj_t * ui_BarValuePM10;
lv_obj_t * ui_LabelNamePM10;
lv_obj_t * ui_ContainerLinePM10;
lv_obj_t * ui_ContainerCoverCO2;
lv_obj_t * ui_PanelCO2;
lv_obj_t * ui_ContainerCO2;
lv_obj_t * ui_ImageIconCO2;
lv_obj_t * ui_ContainerDataCO2;
lv_obj_t * ui_ContainerLabelDataCO2;
lv_obj_t * ui_LabelValueCO2;
lv_obj_t * ui_LabelUnitCO2;
lv_obj_t * ui_BarValueCO2;
lv_obj_t * ui_LabelNameCO2;
lv_obj_t * ui_PanelLineCenterLeft;
lv_obj_t * ui_ContainerIndicator;
lv_obj_t * ui_ContainerMain;
lv_obj_t * ui_ContainerSelectAQI;
lv_obj_t * ui_LabelValueSelectAQI;
lv_obj_t * ui_ContaierInforSelectAQI;
lv_obj_t * ui_ContainerLevelSelectAQI;
lv_obj_t * ui_ContainerAlignLevelSelectAQI;
lv_obj_t * ui_ImageLevelSelectAQI;
lv_obj_t * ui_LabelUnitSelectAQI;
lv_obj_t * ui_ContainerNameSelectAQI;
lv_obj_t * ui_LabelNameSelectAQI;
lv_obj_t * ui_PanelLineCenterRight;
lv_obj_t * ui_ContainerRegionRight;
lv_obj_t * ui_ContainerCoverTEMP;
lv_obj_t * ui_PanelTEMP;
lv_obj_t * ui_ContainerTEMP;
lv_obj_t * ui_ImageIconTEMP;
lv_obj_t * ui_ContainerDataTEMP;
lv_obj_t * ui_ContainerLabelDataTEMP;
lv_obj_t * ui_LabelValueTEMP;
lv_obj_t * ui_LabelUnitTEMP;
lv_obj_t * ui_BarValueTEMP;
lv_obj_t * ui_LabelNameTEMP;
lv_obj_t * ui_ContainerLineTEMP;
lv_obj_t * ui_ContainerCoverRH;
lv_obj_t * ui_PanelRH;
lv_obj_t * ui_ContainerRH;
lv_obj_t * ui_ImageIconRH;
lv_obj_t * ui_ContainerDataRH;
lv_obj_t * ui_ContainerLabelDataRH;
lv_obj_t * ui_LabelValueRH;
lv_obj_t * ui_LabelUnitRH;
lv_obj_t * ui_BarValueRH;
lv_obj_t * ui_LabelNameRH;
lv_obj_t * ui_ContainerLineRH;
lv_obj_t * ui_ContainerCoverTVOC;
lv_obj_t * ui_PanelTVOC;
lv_obj_t * ui_ContainerTVOC;
lv_obj_t * ui_ImageIconTVOC;
lv_obj_t * ui_ContainerDataTVOC;
lv_obj_t * ui_ContainerLabelDataTVOC;
lv_obj_t * ui_LabelValueTVOC;
lv_obj_t * ui_LabelUnitTVOC;
lv_obj_t * ui_BarValueTVOC;
lv_obj_t * ui_LabelNameTVOC;
lv_obj_t * ui_ContainerLineTVOC;
lv_obj_t * ui_ContainerCoverAQI;
lv_obj_t * ui_PanelAQI;
lv_obj_t * ui_ContainerAQI;
lv_obj_t * ui_ImageIconAQI;
lv_obj_t * ui_ContainerDataAQI;
lv_obj_t * ui_ContainerLabelDataAQI;
lv_obj_t * ui_LabelValueAQI;
lv_obj_t * ui_LabelUnitAQI;
lv_obj_t * ui_BarValueAQI;
lv_obj_t * ui_LabelNameAQI;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_co[1] = {&ui_img_images_co2_png};
const lv_img_dsc_t * ui_imgset_flag_be_[1] = {&ui_img_images_flag_be_44_png};
const lv_img_dsc_t * ui_imgset_flag_de_[1] = {&ui_img_images_flag_de_44_png};
const lv_img_dsc_t * ui_imgset_flag_en_[1] = {&ui_img_images_flag_en_44_png};
const lv_img_dsc_t * ui_imgset_flag_es_[1] = {&ui_img_images_flag_es_44_png};
const lv_img_dsc_t * ui_imgset_flag_pl_[1] = {&ui_img_images_flag_pl_44_png};
const lv_img_dsc_t * ui_imgset_flag_pt_[1] = {&ui_img_images_flag_pt_44_png};
const lv_img_dsc_t * ui_imgset_flag_ro_[1] = {&ui_img_images_flag_ro_44_png};
const lv_img_dsc_t * ui_imgset_flag_sv_[1] = {&ui_img_images_flag_sv_44_png};
const lv_img_dsc_t * ui_imgset_flag_tr_[1] = {&ui_img_images_flag_tr_44_png};
const lv_img_dsc_t * ui_imgset_wifi_[1] = {&ui_img_images_wifi_44_png};
const lv_img_dsc_t * ui_imgset_wifi_blue_[1] = {&ui_img_images_wifi_blue_24_png};
const lv_img_dsc_t * ui_imgset_wifi_white_[1] = {&ui_img_images_wifi_white_24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenLoadAQI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenSettingAQI, LV_SCR_LOAD_ANIM_FADE_ON, 300, 1250, &ui_ScreenSettingAQI_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    aqi_config_theme_t * theme_config = aqi_config_theme_get();
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(theme_config->color_primary),
                                                      lv_palette_main(theme_config->color_secondary),
                                                      theme_config->dark_mode, LV_FONT_DEFAULT);

    lv_disp_set_theme(dispp, theme);
    ui_ScreenLoadAQI_screen_init();
    ui_ScreenSettingAQI_screen_init();
    ui_ScreenIndicatorAQI_screen_init();

    aqi_indicator_ui_init();
    aqi_setting_init();
    aqi_utility_init();
    aqi_sensor_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLoadAQI);
}
