// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#ifndef _ESP32S3_AIR_MON_UI_H
#define _ESP32S3_AIR_MON_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "aqi_indicator_ui.h"
#include "aqi_sensor.h"

// SCREEN: ui_ScreenLoadAQI
void ui_ScreenLoadAQI_screen_init(void);
void ui_event_ScreenLoadAQI(lv_event_t * e);
extern lv_obj_t * ui_ScreenLoadAQI;
extern lv_obj_t * ui_ContainerLoad;
extern lv_obj_t * ui_ContainerLoadStatus;
extern lv_obj_t * ui_ContaierLoadLeftSide;
extern lv_obj_t * ui_LabelLoadTime;
extern lv_obj_t * ui_ContainerLoadRightSide;
extern lv_obj_t * ui_ContainerLoadMobileSignal;
extern lv_obj_t * ui_ImageLoadMobileSignal;
extern lv_obj_t * ui_ContainerLoadWifi;
extern lv_obj_t * ui_ImageLoadWifi;
extern lv_obj_t * ui_ContainerLoadBattery;
extern lv_obj_t * ui_ImageLoadBattery;
extern lv_obj_t * ui_BarLoadBattery;
extern lv_obj_t * ui_ContainerLoadMain;
extern lv_obj_t * ui_SpinnerLoadProgress;
extern lv_obj_t * ui_ContainerLoading;
extern lv_obj_t * ui_ContainerLoadName;
extern lv_obj_t * ui_ImageLoadName;
extern lv_obj_t * ui_LabelLoading;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenIndicatorAQI
void ui_ScreenIndicatorAQI_screen_init(void);
extern lv_obj_t * ui_ScreenIndicatorAQI;
extern lv_obj_t * ui_ContainerRegionLeft;
void ui_event_ContainerCoverPM1(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverPM1;
void ui_event_PanelPM1(lv_event_t * e);
extern lv_obj_t * ui_PanelPM1;
extern lv_obj_t * ui_ContainerPM1;
extern lv_obj_t * ui_ImageIconPM1;
extern lv_obj_t * ui_ContainerDataPM1;
extern lv_obj_t * ui_ContainerLabelDataPM1;
extern lv_obj_t * ui_LabelValuePM1;
extern lv_obj_t * ui_LabelUnitPM1;
extern lv_obj_t * ui_BarValuePM1;
extern lv_obj_t * ui_LabelNamePM1;
void ui_event_ContainerLinePM1(lv_event_t * e);
extern lv_obj_t * ui_ContainerLinePM1;
void ui_event_ContainerCoverPM25(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverPM25;
void ui_event_PanelPM25(lv_event_t * e);
extern lv_obj_t * ui_PanelPM25;
extern lv_obj_t * ui_ContainerPM25;
extern lv_obj_t * ui_ImageIconPM25;
extern lv_obj_t * ui_ContainerDataPM25;
extern lv_obj_t * ui_ContainerLabelDataPM25;
extern lv_obj_t * ui_LabelValuePM25;
extern lv_obj_t * ui_LabelUnitPM25;
extern lv_obj_t * ui_BarValuePM25;
extern lv_obj_t * ui_LabelNamePM25;
void ui_event_ContainerLinePM25(lv_event_t * e);
extern lv_obj_t * ui_ContainerLinePM25;
void ui_event_ContainerCoverPM10(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverPM10;
void ui_event_PanelPM10(lv_event_t * e);
extern lv_obj_t * ui_PanelPM10;
extern lv_obj_t * ui_ContainerPM10;
extern lv_obj_t * ui_ImageIconPM10;
extern lv_obj_t * ui_ContainerDataPM10;
extern lv_obj_t * ui_ContainerLabelDataPM10;
extern lv_obj_t * ui_LabelValuePM10;
extern lv_obj_t * ui_LabelUnitPM10;
extern lv_obj_t * ui_BarValuePM10;
extern lv_obj_t * ui_LabelNamePM10;
void ui_event_ContainerLinePM10(lv_event_t * e);
extern lv_obj_t * ui_ContainerLinePM10;
void ui_event_ContainerCoverCO2(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverCO2;
void ui_event_PanelCO2(lv_event_t * e);
extern lv_obj_t * ui_PanelCO2;
extern lv_obj_t * ui_ContainerCO2;
extern lv_obj_t * ui_ImageIconCO2;
extern lv_obj_t * ui_ContainerDataCO2;
extern lv_obj_t * ui_ContainerLabelDataCO2;
extern lv_obj_t * ui_LabelValueCO2;
extern lv_obj_t * ui_LabelUnitCO2;
extern lv_obj_t * ui_BarValueCO2;
extern lv_obj_t * ui_LabelNameCO2;
extern lv_obj_t * ui_PanelLineCenterLeft;
extern lv_obj_t * ui_ContainerRegionCenter;
extern lv_obj_t * ui_ContainerStatus;
extern lv_obj_t * ui_ContaierLeftSide;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ContainerRightSide;
extern lv_obj_t * ui_ContainerMobileSignal;
extern lv_obj_t * ui_ImageMobileSignal;
extern lv_obj_t * ui_ContainerWifi;
extern lv_obj_t * ui_ImageWifi;
extern lv_obj_t * ui_ContainerBattery;
extern lv_obj_t * ui_ImageBattery;
extern lv_obj_t * ui_BarBattery;
extern lv_obj_t * ui_ContainerMain;
extern lv_obj_t * ui_ContainerSelectAQI;
extern lv_obj_t * ui_LabelValueSelectAQI;
extern lv_obj_t * ui_ContaierInforSelectAQI;
extern lv_obj_t * ui_ContainerLevelSelectAQI;
extern lv_obj_t * ui_ContainerAlignLevelSelectAQI;
extern lv_obj_t * ui_ImageLevelSelectAQI;
extern lv_obj_t * ui_LabelUnitSelectAQI;
extern lv_obj_t * ui_ContainerNameSelectAQI;
extern lv_obj_t * ui_LabelNameSelectAQI;
extern lv_obj_t * ui_PanelLineCenterRight;
extern lv_obj_t * ui_ContainerRegionRight;
void ui_event_ContainerCoverTEMP(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverTEMP;
void ui_event_PanelTEMP(lv_event_t * e);
extern lv_obj_t * ui_PanelTEMP;
extern lv_obj_t * ui_ContainerTEMP;
extern lv_obj_t * ui_ImageIconTEMP;
extern lv_obj_t * ui_ContainerDataTEMP;
extern lv_obj_t * ui_ContainerLabelDataTEMP;
extern lv_obj_t * ui_LabelValueTEMP;
extern lv_obj_t * ui_LabelUnitTEMP;
extern lv_obj_t * ui_BarValueTEMP;
extern lv_obj_t * ui_LabelNameTEMP;
void ui_event_ContainerLineTEMP(lv_event_t * e);
extern lv_obj_t * ui_ContainerLineTEMP;
void ui_event_ContainerCoverRH(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverRH;
void ui_event_PanelRH(lv_event_t * e);
extern lv_obj_t * ui_PanelRH;
extern lv_obj_t * ui_ContainerRH;
extern lv_obj_t * ui_ImageIconRH;
extern lv_obj_t * ui_ContainerDataRH;
extern lv_obj_t * ui_ContainerLabelDataRH;
extern lv_obj_t * ui_LabelValueRH;
extern lv_obj_t * ui_LabelUnitRH;
extern lv_obj_t * ui_BarValueRH;
extern lv_obj_t * ui_LabelNameRH;
void ui_event_ContainerLineRH(lv_event_t * e);
extern lv_obj_t * ui_ContainerLineRH;
void ui_event_ContainerCoverTVOC(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverTVOC;
void ui_event_PanelTVOC(lv_event_t * e);
extern lv_obj_t * ui_PanelTVOC;
extern lv_obj_t * ui_ContainerTVOC;
extern lv_obj_t * ui_ImageIconTVOC;
extern lv_obj_t * ui_ContainerDataTVOC;
extern lv_obj_t * ui_ContainerLabelDataTVOC;
extern lv_obj_t * ui_LabelValueTVOC;
extern lv_obj_t * ui_LabelUnitTVOC;
extern lv_obj_t * ui_BarValueTVOC;
extern lv_obj_t * ui_LabelNameTVOC;
void ui_event_ContainerLineTVOC(lv_event_t * e);
extern lv_obj_t * ui_ContainerLineTVOC;
void ui_event_ContainerCoverSetting(lv_event_t * e);
extern lv_obj_t * ui_ContainerCoverSetting;
void ui_event_PanelSetting(lv_event_t * e);
extern lv_obj_t * ui_PanelSetting;
extern lv_obj_t * ui_ContainerSetting;
extern lv_obj_t * ui_ImageIconSetting;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_mobilesignal4_png);    // assets/Images/MobileSignal4.png
LV_IMG_DECLARE(ui_img_images_wifi3_png);    // assets/Images/Wifi3.png
LV_IMG_DECLARE(ui_img_images_batteryoutline_png);    // assets/Images/BatteryOutline.png
LV_IMG_DECLARE(ui_img_images_line_png);    // assets/Images/Line.png
LV_IMG_DECLARE(ui_img_images_load_png);    // assets/Images/load.png
LV_IMG_DECLARE(ui_img_images_pm_white_png);    // assets/Images/PM_White.png
LV_IMG_DECLARE(ui_img_images_co2_white_png);    // assets/Images/CO2_White.png
LV_IMG_DECLARE(ui_img_images_temp_white_png);    // assets/Images/TEMP_White.png
LV_IMG_DECLARE(ui_img_images_rh_white_png);    // assets/Images/RH_White.png
LV_IMG_DECLARE(ui_img_images_tvoc_white_png);    // assets/Images/TVOC_White.png
LV_IMG_DECLARE(ui_img_images_setting32_32_png);    // assets/Images/Setting32_32.png
LV_IMG_DECLARE(ui_img_images_co2_green_png);    // assets/Images/CO2_Green.png
LV_IMG_DECLARE(ui_img_images_co2_orange_png);    // assets/Images/CO2_Orange.png
LV_IMG_DECLARE(ui_img_images_co2_red_png);    // assets/Images/CO2_Red.png
LV_IMG_DECLARE(ui_img_images_pm_green_png);    // assets/Images/PM_Green.png
LV_IMG_DECLARE(ui_img_images_pm_orange_png);    // assets/Images/PM_Orange.png
LV_IMG_DECLARE(ui_img_images_pm_red_png);    // assets/Images/PM_Red.png
LV_IMG_DECLARE(ui_img_images_rh_green_png);    // assets/Images/RH_Green.png
LV_IMG_DECLARE(ui_img_images_rh_orange_png);    // assets/Images/RH_Orange.png
LV_IMG_DECLARE(ui_img_images_rh_red_png);    // assets/Images/RH_Red.png
LV_IMG_DECLARE(ui_img_images_temp_green_png);    // assets/Images/TEMP_Green.png
LV_IMG_DECLARE(ui_img_images_temp_orange_png);    // assets/Images/TEMP_Orange.png
LV_IMG_DECLARE(ui_img_images_temp_red_png);    // assets/Images/TEMP_Red.png
LV_IMG_DECLARE(ui_img_images_tvoc_green_png);    // assets/Images/TVOC_Green.png
LV_IMG_DECLARE(ui_img_images_tvoc_orange_png);    // assets/Images/TVOC_Orange.png
LV_IMG_DECLARE(ui_img_images_tvoc_red_png);    // assets/Images/TVOC_Red.png
LV_IMG_DECLARE(ui_img_images_wifi1_png);    // assets/Images/Wifi1.png
LV_IMG_DECLARE(ui_img_images_wifi2_png);    // assets/Images/Wifi2.png

// FONTS
LV_FONT_DECLARE(ui_font_OpenSans_Regular_14);
LV_FONT_DECLARE(ui_font_OpenSans_Regular_16);
LV_FONT_DECLARE(ui_font_Poppins_ExtraLight_116);
LV_FONT_DECLARE(ui_font_Poppins_Light_18);
LV_FONT_DECLARE(ui_font_Poppins_Light_20);
LV_FONT_DECLARE(ui_font_Poppins_Light_24);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
