// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#ifndef _ESP32S3_AIR_MON_UI_H
#define _ESP32S3_AIR_MON_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

#include "aqi_config.h"
#include "aqi_utility.h"
#include "aqi_indicator_ui.h"
#include "aqi_setting.h"
#include "aqi_sensor.h"

// SCREEN: ui_ScreenLoadAQI
void ui_ScreenLoadAQI_screen_init(void);
void ui_event_ScreenLoadAQI(lv_event_t * e);
extern lv_obj_t * ui_ScreenLoadAQI;
extern lv_obj_t * ui_ContainerLoad;
extern lv_obj_t * ui_ContainerStatus;
extern lv_obj_t * ui_ContaierStatusLeft;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ContainerStatusRight;
extern lv_obj_t * ui_ContainerMobileSignal;
extern lv_obj_t * ui_ImageMobileSignal;
extern lv_obj_t * ui_ContainerWifiSignal;
extern lv_obj_t * ui_ImageWifiSignal;
extern lv_obj_t * ui_ContainerBattery;
extern lv_obj_t * ui_ImageBattery;
extern lv_obj_t * ui_BarBattery;
extern lv_obj_t * ui_ContainerLoadMain;
extern lv_obj_t * ui_SpinnerLoadProgress;
extern lv_obj_t * ui_ContainerLoading;
extern lv_obj_t * ui_ContainerLoadName;
extern lv_obj_t * ui_ImageLoadName;
extern lv_obj_t * ui_LabelLoading;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSettingAQI
void ui_ScreenSettingAQI_screen_init(void);
extern lv_obj_t * ui_ScreenSettingAQI;
extern lv_obj_t * ui_ContainerSetting;
extern lv_obj_t * ui_ContainerSettingMain;
extern lv_obj_t * ui_ContainerSettingTab;
extern lv_obj_t * ui_ContainerSettingTabHeader;
extern lv_obj_t * ui_ImageSettingTabSwitchBack;
extern lv_obj_t * ui_LabelSettingTabTitleName;
extern lv_obj_t * ui_SwitchSettingTabDarkMode;
extern lv_obj_t * ui_ContainerSettingTabBody;
extern lv_obj_t * ui_ContainerSettingTabBody1;
extern lv_obj_t * ui_ContainerSettingTabSound;
extern lv_obj_t * ui_ContainerSettingTabSoundIcon;
extern lv_obj_t * ui_ImageSettingTabSoundIcon;
extern lv_obj_t * ui_LabelSettingTabSoundName;
extern lv_obj_t * ui_SwitchSettingTabSoundEnable;
extern lv_obj_t * ui_ContainerSettingTabWifi;
extern lv_obj_t * ui_ContainerSettingTabWifiIcon;
extern lv_obj_t * ui_ImageSettingTabWifiIcon;
extern lv_obj_t * ui_LabelSettingTabWifiName;
extern lv_obj_t * ui_SwitchSettingTabWifiEnable;
extern lv_obj_t * ui_ContainerSettingTabHistory;
extern lv_obj_t * ui_ContainerSettingTabHistoryIcon;
extern lv_obj_t * ui_ImageSettingTabHistoryIcon;
extern lv_obj_t * ui_LabelSettingTabHistoryName;
extern lv_obj_t * ui_SwitchSettingTabHistoryEnable;
extern lv_obj_t * ui_ContainerSettingTabBody2;
extern lv_obj_t * ui_ContainerSettingTabLanguage;
extern lv_obj_t * ui_ImageSettingTabLanguageIcon;
extern lv_obj_t * ui_LabelSettingTabLanguageName;
extern lv_obj_t * ui_ImageSettingTabLanguageChange;
extern lv_obj_t * ui_ContainerSettingTabCountry;
extern lv_obj_t * ui_ImageSettingTabCountryIcon;
extern lv_obj_t * ui_LabelSettingTabCountryName;
extern lv_obj_t * ui_ImageSettingTabCountryChange;
extern lv_obj_t * ui_ContainerSettingTabBody3;
extern lv_obj_t * ui_ContainerSettingTabBluetooth;
extern lv_obj_t * ui_ContainerSettingTabBluetoothIcon;
extern lv_obj_t * ui_ImageSettingTabBluetoothIcon;
extern lv_obj_t * ui_LabelSettingTabBluetoothName;
extern lv_obj_t * ui_SwitchSettingTabBluetoothEnable;
extern lv_obj_t * ui_ContainerSettingTabEmailAlert;
extern lv_obj_t * ui_ContainerSettingTabEmailAlertIcon;
extern lv_obj_t * ui_ImageSettingTabEmailAlertIcon;
extern lv_obj_t * ui_LabelSettingTabEmailAlertName;
extern lv_obj_t * ui_SwitchSettingTabEmailAlertEnable;
extern lv_obj_t * ui_ContainerSettingTabBody4;
extern lv_obj_t * ui_ContainerSettingTabWeb;
extern lv_obj_t * ui_ContainerSettingTabWebIcon;
extern lv_obj_t * ui_ImageSettingTabWebIcon;
extern lv_obj_t * ui_LabelSettingTabWebName;
extern lv_obj_t * ui_ImageSettingTabWebEdit;
extern lv_obj_t * ui_ContainerSettingTabEmail;
extern lv_obj_t * ui_ContainerSettingTabEmailIcon;
extern lv_obj_t * ui_ImageSettingTabEmailIcon;
extern lv_obj_t * ui_LabelSettingTabEmailName;
extern lv_obj_t * ui_ImageSettingTabEmailEdit;
extern lv_obj_t * ui_ContainerSettingLanguage;
extern lv_obj_t * ui_ContainerSettingLanguageTitle;
extern lv_obj_t * ui_ImageSettingLanguageTitleIcon;
extern lv_obj_t * ui_LabelSettingLanguageTitleName;
extern lv_obj_t * ui_ContainerSettingCountry;
extern lv_obj_t * ui_ContainerSettingCountryTitle;
extern lv_obj_t * ui_ImageSettingCountryTitleIcon;
extern lv_obj_t * ui_LabelSettingCountryTitleName;
extern lv_obj_t * ui_ContainerSettingWifi;
extern lv_obj_t * ui_ContainerSettingWifiTitle;
extern lv_obj_t * ui_ImageSettingWifiTitleIcon;
extern lv_obj_t * ui_LabelSettingWifiTitleName;
extern lv_obj_t * ui_ContainerSettingWifiEnable;
extern lv_obj_t * ui_ContainerSettingWifiEnableIcon;
extern lv_obj_t * ui_ImageSettingWifiEnableIcon;
extern lv_obj_t * ui_LabelSettingWifiEnable;
extern lv_obj_t * ui_SwitchSettingWifiEnable;
extern lv_obj_t * ui_ContainerSettingButton;
extern lv_obj_t * ui_ButtonSettingBack;
extern lv_obj_t * ui_LabelSettingBackButton;
extern lv_obj_t * ui_ButtonSettingNext;
extern lv_obj_t * ui_LabelSettingNextButton;
extern lv_obj_t * ui_ContainerSettingStage;
extern lv_obj_t * ui_ImageSettingStageLanguage;
extern lv_obj_t * ui_ImageSettingStageCountry;
extern lv_obj_t * ui_ImageSettingStageWifi;
extern lv_obj_t * ui_ButtonSettingSelect;
extern lv_obj_t * ui_LabelSettingSelectButton;
extern lv_obj_t * ui_ContainerWifiPassword;
extern lv_obj_t * ui_ContainerWifiSelect;
extern lv_obj_t * ui_ContainerWifiSelectIcon;
extern lv_obj_t * ui_ImageWifiSelectIcon;
extern lv_obj_t * ui_LabelWifiSelectName;
extern lv_obj_t * ui_ImageWifiSelectExit;
extern lv_obj_t * ui_ContainerWifiPasswordType;
extern lv_obj_t * ui_ImageWifiPasswordLock;
extern lv_obj_t * ui_TextWifiPasswordType;
extern lv_obj_t * ui_LabelWifiPasswordShow;
extern lv_obj_t * ui_ButtonWifiConnect;
extern lv_obj_t * ui_LabelWifiConnectButton;
extern lv_obj_t * ui_KeyboardWifiPassword;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenIndicatorAQI
void ui_ScreenIndicatorAQI_screen_init(void);
extern lv_obj_t * ui_ScreenIndicatorAQI;
extern lv_obj_t * ui_ContainerRegionLeft;
extern lv_obj_t * ui_ContainerCoverPM1;
extern lv_obj_t * ui_PanelPM1;
extern lv_obj_t * ui_ContainerPM1;
extern lv_obj_t * ui_ImageIconPM1;
extern lv_obj_t * ui_ContainerDataPM1;
extern lv_obj_t * ui_ContainerLabelDataPM1;
extern lv_obj_t * ui_LabelValuePM1;
extern lv_obj_t * ui_LabelUnitPM1;
extern lv_obj_t * ui_BarValuePM1;
extern lv_obj_t * ui_LabelNamePM1;
extern lv_obj_t * ui_ContainerLinePM1;
extern lv_obj_t * ui_ContainerCoverPM25;
extern lv_obj_t * ui_PanelPM25;
extern lv_obj_t * ui_ContainerPM25;
extern lv_obj_t * ui_ImageIconPM25;
extern lv_obj_t * ui_ContainerDataPM25;
extern lv_obj_t * ui_ContainerLabelDataPM25;
extern lv_obj_t * ui_LabelValuePM25;
extern lv_obj_t * ui_LabelUnitPM25;
extern lv_obj_t * ui_BarValuePM25;
extern lv_obj_t * ui_LabelNamePM25;
extern lv_obj_t * ui_ContainerLinePM25;
extern lv_obj_t * ui_ContainerCoverPM10;
extern lv_obj_t * ui_PanelPM10;
extern lv_obj_t * ui_ContainerPM10;
extern lv_obj_t * ui_ImageIconPM10;
extern lv_obj_t * ui_ContainerDataPM10;
extern lv_obj_t * ui_ContainerLabelDataPM10;
extern lv_obj_t * ui_LabelValuePM10;
extern lv_obj_t * ui_LabelUnitPM10;
extern lv_obj_t * ui_BarValuePM10;
extern lv_obj_t * ui_LabelNamePM10;
extern lv_obj_t * ui_ContainerLinePM10;
extern lv_obj_t * ui_ContainerCoverCO2;
extern lv_obj_t * ui_PanelCO2;
extern lv_obj_t * ui_ContainerCO2;
extern lv_obj_t * ui_ImageIconCO2;
extern lv_obj_t * ui_ContainerDataCO2;
extern lv_obj_t * ui_ContainerLabelDataCO2;
extern lv_obj_t * ui_LabelValueCO2;
extern lv_obj_t * ui_LabelUnitCO2;
extern lv_obj_t * ui_BarValueCO2;
extern lv_obj_t * ui_LabelNameCO2;
extern lv_obj_t * ui_PanelLineCenterLeft;
extern lv_obj_t * ui_ContainerIndicator;
extern lv_obj_t * ui_ContainerMain;
extern lv_obj_t * ui_ContainerSelectAQI;
extern lv_obj_t * ui_LabelValueSelectAQI;
extern lv_obj_t * ui_ContaierInforSelectAQI;
extern lv_obj_t * ui_ContainerLevelSelectAQI;
extern lv_obj_t * ui_ContainerAlignLevelSelectAQI;
extern lv_obj_t * ui_ImageLevelSelectAQI;
extern lv_obj_t * ui_LabelUnitSelectAQI;
extern lv_obj_t * ui_ContainerNameSelectAQI;
extern lv_obj_t * ui_LabelNameSelectAQI;
extern lv_obj_t * ui_PanelLineCenterRight;
extern lv_obj_t * ui_ContainerRegionRight;
extern lv_obj_t * ui_ContainerCoverTEMP;
extern lv_obj_t * ui_PanelTEMP;
extern lv_obj_t * ui_ContainerTEMP;
extern lv_obj_t * ui_ImageIconTEMP;
extern lv_obj_t * ui_ContainerDataTEMP;
extern lv_obj_t * ui_ContainerLabelDataTEMP;
extern lv_obj_t * ui_LabelValueTEMP;
extern lv_obj_t * ui_LabelUnitTEMP;
extern lv_obj_t * ui_BarValueTEMP;
extern lv_obj_t * ui_LabelNameTEMP;
extern lv_obj_t * ui_ContainerLineTEMP;
extern lv_obj_t * ui_ContainerCoverRH;
extern lv_obj_t * ui_PanelRH;
extern lv_obj_t * ui_ContainerRH;
extern lv_obj_t * ui_ImageIconRH;
extern lv_obj_t * ui_ContainerDataRH;
extern lv_obj_t * ui_ContainerLabelDataRH;
extern lv_obj_t * ui_LabelValueRH;
extern lv_obj_t * ui_LabelUnitRH;
extern lv_obj_t * ui_BarValueRH;
extern lv_obj_t * ui_LabelNameRH;
extern lv_obj_t * ui_ContainerLineRH;
extern lv_obj_t * ui_ContainerCoverTVOC;
extern lv_obj_t * ui_PanelTVOC;
extern lv_obj_t * ui_ContainerTVOC;
extern lv_obj_t * ui_ImageIconTVOC;
extern lv_obj_t * ui_ContainerDataTVOC;
extern lv_obj_t * ui_ContainerLabelDataTVOC;
extern lv_obj_t * ui_LabelValueTVOC;
extern lv_obj_t * ui_LabelUnitTVOC;
extern lv_obj_t * ui_BarValueTVOC;
extern lv_obj_t * ui_LabelNameTVOC;
extern lv_obj_t * ui_ContainerLineTVOC;
extern lv_obj_t * ui_ContainerCoverSetting;
extern lv_obj_t * ui_PanelSetting;
extern lv_obj_t * ui_ContainerSettingIcon;
extern lv_obj_t * ui_ImageSettingIcon;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_mobilesignal_png);    // assets/Images/MobileSignal.png
LV_IMG_DECLARE(ui_img_images_batteryoutline_png);    // assets/Images/BatteryOutline.png
LV_IMG_DECLARE(ui_img_images_load_spinner_png);    // assets/Images/Load_Spinner.png
LV_IMG_DECLARE(ui_img_images_load_en_us_png);    // assets/Images/Load_en_US.png
LV_IMG_DECLARE(ui_img_images_switch_back_png);    // assets/Images/Switch_Back.png
LV_IMG_DECLARE(ui_img_images_light_mode_select_png);    // assets/Images/Light_Mode_Select.png
LV_IMG_DECLARE(ui_img_images_light_mode_deselect_png);    // assets/Images/Light_Mode_Deselect.png
LV_IMG_DECLARE(ui_img_images_dark_mode_deselect_png);    // assets/Images/Dark_Mode_Deselect.png
LV_IMG_DECLARE(ui_img_images_dark_mode_select_png);    // assets/Images/Dark_Mode_Select.png
LV_IMG_DECLARE(ui_img_images_sound_png);    // assets/Images/Sound.png
LV_IMG_DECLARE(ui_img_images_wifi_white_24_png);    // assets/Images/Wifi_White_24.png
LV_IMG_DECLARE(ui_img_images_history_png);    // assets/Images/History.png
LV_IMG_DECLARE(ui_img_images_flag_en_44_png);    // assets/Images/Flag_EN_44.png
LV_IMG_DECLARE(ui_img_images_change_png);    // assets/Images/Change.png
LV_IMG_DECLARE(ui_img_images_bluetooth_png);    // assets/Images/Bluetooth.png
LV_IMG_DECLARE(ui_img_images_email_png);    // assets/Images/Email.png
LV_IMG_DECLARE(ui_img_images_web_png);    // assets/Images/Web.png
LV_IMG_DECLARE(ui_img_images_edit_png);    // assets/Images/Edit.png
LV_IMG_DECLARE(ui_img_images_language_png);    // assets/Images/Language.png
LV_IMG_DECLARE(ui_img_images_country_png);    // assets/Images/Country.png
LV_IMG_DECLARE(ui_img_images_wifi_44_png);    // assets/Images/Wifi_44.png
LV_IMG_DECLARE(ui_img_images_wifi_blue_24_png);    // assets/Images/Wifi_Blue_24.png
LV_IMG_DECLARE(ui_img_images_stage_grey_png);    // assets/Images/Stage_Grey.png
LV_IMG_DECLARE(ui_img_images_exit_png);    // assets/Images/Exit.png
LV_IMG_DECLARE(ui_img_images_wifi_lock_select_png);    // assets/Images/Wifi_Lock_Select.png
LV_IMG_DECLARE(ui_img_images_aqi_png);    // assets/Images/AQI.png
LV_IMG_DECLARE(ui_img_images_aqi_bad_png);    // assets/Images/AQI_Bad.png
LV_IMG_DECLARE(ui_img_images_aqi_good_png);    // assets/Images/AQI_Good.png
LV_IMG_DECLARE(ui_img_images_aqi_warning_png);    // assets/Images/AQI_Warning.png
LV_IMG_DECLARE(ui_img_images_batteryoutline_png);    // assets/Images/BatteryOutline.png
LV_IMG_DECLARE(ui_img_images_co2_png);    // assets/Images/CO2.png
LV_IMG_DECLARE(ui_img_images_co2_bad_png);    // assets/Images/CO2_Bad.png
LV_IMG_DECLARE(ui_img_images_co2_good_png);    // assets/Images/CO2_Good.png
LV_IMG_DECLARE(ui_img_images_co2_warning_png);    // assets/Images/CO2_Warning.png
LV_IMG_DECLARE(ui_img_images_flag_be_png);    // assets/Images/Flag_BE.png
LV_IMG_DECLARE(ui_img_images_flag_be_44_png);    // assets/Images/Flag_BE_44.png
LV_IMG_DECLARE(ui_img_images_flag_de_png);    // assets/Images/Flag_DE.png
LV_IMG_DECLARE(ui_img_images_flag_de_44_png);    // assets/Images/Flag_DE_44.png
LV_IMG_DECLARE(ui_img_images_flag_en_png);    // assets/Images/Flag_EN.png
LV_IMG_DECLARE(ui_img_images_flag_es_png);    // assets/Images/Flag_ES.png
LV_IMG_DECLARE(ui_img_images_flag_es_44_png);    // assets/Images/Flag_ES_44.png
LV_IMG_DECLARE(ui_img_images_flag_pl_png);    // assets/Images/Flag_PL.png
LV_IMG_DECLARE(ui_img_images_flag_pl_44_png);    // assets/Images/Flag_PL_44.png
LV_IMG_DECLARE(ui_img_images_flag_pt_png);    // assets/Images/Flag_PT.png
LV_IMG_DECLARE(ui_img_images_flag_pt_44_png);    // assets/Images/Flag_PT_44.png
LV_IMG_DECLARE(ui_img_images_flag_ro_png);    // assets/Images/Flag_RO.png
LV_IMG_DECLARE(ui_img_images_flag_ro_44_png);    // assets/Images/Flag_RO_44.png
LV_IMG_DECLARE(ui_img_images_flag_sv_png);    // assets/Images/Flag_SV.png
LV_IMG_DECLARE(ui_img_images_flag_sv_44_png);    // assets/Images/Flag_SV_44.png
LV_IMG_DECLARE(ui_img_images_flag_tr_png);    // assets/Images/Flag_TR.png
LV_IMG_DECLARE(ui_img_images_flag_tr_44_png);    // assets/Images/Flag_TR_44.png
LV_IMG_DECLARE(ui_img_images_pm_png);    // assets/Images/PM.png
LV_IMG_DECLARE(ui_img_images_pm_bad_png);    // assets/Images/PM_Bad.png
LV_IMG_DECLARE(ui_img_images_pm_good_png);    // assets/Images/PM_Good.png
LV_IMG_DECLARE(ui_img_images_pm_warning_png);    // assets/Images/PM_Warning.png
LV_IMG_DECLARE(ui_img_images_rh_png);    // assets/Images/RH.png
LV_IMG_DECLARE(ui_img_images_rh_bad_png);    // assets/Images/RH_Bad.png
LV_IMG_DECLARE(ui_img_images_rh_good_png);    // assets/Images/RH_Good.png
LV_IMG_DECLARE(ui_img_images_rh_warning_png);    // assets/Images/RH_Warning.png
LV_IMG_DECLARE(ui_img_images_setting_png);    // assets/Images/Setting.png
LV_IMG_DECLARE(ui_img_images_stage_green_png);    // assets/Images/Stage_Green.png
LV_IMG_DECLARE(ui_img_images_temp_png);    // assets/Images/TEMP.png
LV_IMG_DECLARE(ui_img_images_temp_bad_png);    // assets/Images/TEMP_Bad.png
LV_IMG_DECLARE(ui_img_images_temp_good_png);    // assets/Images/TEMP_Good.png
LV_IMG_DECLARE(ui_img_images_temp_warning_png);    // assets/Images/TEMP_Warning.png
LV_IMG_DECLARE(ui_img_images_tick_png);    // assets/Images/Tick.png
LV_IMG_DECLARE(ui_img_images_tvoc_png);    // assets/Images/TVOC.png
LV_IMG_DECLARE(ui_img_images_tvoc_bad_png);    // assets/Images/TVOC_Bad.png
LV_IMG_DECLARE(ui_img_images_tvoc_good_png);    // assets/Images/TVOC_Good.png
LV_IMG_DECLARE(ui_img_images_tvoc_warning_png);    // assets/Images/TVOC_Warning.png
LV_IMG_DECLARE(ui_img_images_wifi_lock_unselect_png);    // assets/Images/Wifi_Lock_Unselect.png
LV_IMG_DECLARE(ui_img_images_wifi_signal_excellent_png);    // assets/Images/Wifi_Signal_Excellent.png
LV_IMG_DECLARE(ui_img_images_wifi_signal_good_png);    // assets/Images/Wifi_Signal_Good.png
LV_IMG_DECLARE(ui_img_images_wifi_signal_poor_png);    // assets/Images/Wifi_Signal_Poor.png

// FONTS
LV_FONT_DECLARE(ui_font_OpenSans_Regular_14);
LV_FONT_DECLARE(ui_font_OpenSans_Regular_16);
LV_FONT_DECLARE(ui_font_Poppins_ExtraLight_116);
LV_FONT_DECLARE(ui_font_Poppins_Light_18);
LV_FONT_DECLARE(ui_font_Poppins_Light_20);
LV_FONT_DECLARE(ui_font_Poppins_Light_24);
LV_FONT_DECLARE(ui_font_Poppins_Light_36);
LV_FONT_DECLARE(ui_font_Poppins_Regular_18);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
