// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32s3-air-mon

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void aqi_indicator_setting_click_event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
